== Appendix / About Colchester Castle / The Place of James Parnell`'s Imprisonment and death

The following particulars respecting Colchester Castle,
abridged from an account kindly supplied by a Friend of Colchester,
will not be uninteresting to the reader:

[.embedded-content-document]
--

The present Castle at Colchester is so evidently Roman,
that there cannot be a doubt of its having been erected after the conquest,
when fortresses were built in the most considerable towns of England,
with a view to a more complete subjugation of the inhabitants.
It was for many years in the possession of the Crown,
and afterwards passed through several private hands,
one of whom attempted to pull it down for its materials,
but the cement of the walls appeared to be of such strength and solidity
that the sale of the materials was not likely to pay the expenses.
So it was left standing, although much defaced.

It is now much obscured by surrounding houses,
and would escape the notice of a passing traveller, who may be ignorant of its locality.
The structure is square, and flanked at the angles by strong and once lofty towers.
It occupies a surface of more than half an acre.
Its walls are nearly twelve feet thick at the basement, and eleven in the upper story.
In the western wall there are two rows of singular cells or nitches,
which look as if they had been scooped out of the wall; they are about ten feet high,
four feet wide, and three feet deep.
These, perhaps, were formerly built up in front,
and might have been used as solitary dungeons.
There can be no doubt, I think that it was one of these cells,
which formed the last dwelling place of James Parnell.

It appears from William Sewel that he had visited the Castle,
probably with the express view of seeing "`the hole,`"
in which this innocent sufferer was confined.
He describes the cells, as they are mentioned above: "`two rows of vaulted holes.`"
At the time of his visit, the memory of James Parnell must have been still fresh,
so that his testimony is almost as valuable as that of a living witness.
The dimensions of the cell were so small, as scarcely to have permitted James Parnell,
though of very small size, ever to extend himself to full length.
His stretched arms might probably touch the opposite walls, in every direction.
This will give us some idea of the misery and discomfort of his outward situation.
But we have abundant and encouraging evidence that,
in this lonely cell he enjoyed the comfort and support of his Savior`'s presence; and,
like Paul and Silas, had a song of praise put into his mouth in the midst of his enemies.

--
