== The Life of James Parnell

James Parnell was born at Retford, in Nottinghamshire, in 1637.
It is not easy to ascertain the precise station of life in which he moved.
It is stated in the court order by which he was committed to Colchester Castle,
that he was a "`laborer.`"
He says of himself that he was engaged in his "`outward
calling,`" when he was not occupied in the service of Truth:
and that "`he claimed no property in the earth.`"
It is hence probable, that his circumstances were humble.
Our historian, William Sewel,^
footnote:[Author of __The History of the Rise, Increase,
and Progress of that Christian People Called Quakers.__]
informs us that he was "`trained up in the schools of literature;`" a
statement probably derived from a remark of James Parnell,
that he was "`sent unto schools of human learning to learn human wisdom,
for which end the schools are profitable.`"
His writings, however, seem to indicate that,
while he had received an education beyond the medium of that day, it was but limited;
and it certainly was not extended beyond his fourteenth year.
Henry Tuke, with good reason, supposes,
he might have received instruction at the Grammar School at Retford;
and it is highly probable,
that the following remark of James Parnell had reference to the classical authors,
"`Many of the books which are read in the schools of
human learning do much for the corrupting of youth,
and nourishing the wild, profane nature, which then ruled in me.`"

He thus commences a short account, which he wrote while in Colchester Castle,
of his religious experience: "`First,
I shall give the reader a declaration of the work of God in my soul,
and the conversion of my heart from darkness unto His marvelous light;
and from the power of Satan unto God; and from the path of death into the path of life,
where I now walk in the light of my God, with the ransomed of the Lord,
who are traveling towards the holy city:
and also the cause of my coming forth into the world to declare the Truth,
for which I now suffer bonds by the persecuting generation.`"
He says that he was once a child of wrath, as all are by nature,
and followed the vain courses and ways of the world.
His wicked natural propensities were nourished by the education he received; so that,
while at school, and after leaving it, the same depravity of heart remained,
and he grew in sin, and continued to follow the sinful vanities of the world.
He was trained up in the customary worship of the nation,
and attended the service on First-days;
but as his religious exercises were not associated with any real conversion of heart,
and were undertaken in his own carnal will, he afterwards regarded them as mere idolatry.

But, even at this season, while estranged in his heart from God,
and following the gratifications of the carnal mind, he was, from time to time,
sensible of the visitations of heavenly light; not indeed,
then known to him to be of heavenly origin,
but at first "`shining in darkness,`" uncomprehended, as to from where it came,
or to where it was going.
This would spring up in his heart when he was alone,
and reprove him in secret for his transgressions;
by which he was often led into serious self-examination, and consideration of his ways;
and life and death were at times set before his eyes in such a
manner as to cause him to determine to forsake sin.
But, being ignorant that these "`reproofs of instruction`"
were the strivings of the Spirit of Truth with him,
and not yet knowing that all strength and sufficiency
to overcome sin could be derived from God alone,
these determinations were made in his own will,
and were kept only till his resolutions were tested by some fresh temptation,
when the careless mind again wandered,
and "`led him still to delight his heart in the vanity, which the eye saw,
and the ear heard.`"

But the pleasure derived from such vanities passed away with the using,
and he was left to judgments renewed for his transgression;
for the Spirit of Truth still followed him,
"`convinced him of sin,`" and called him to repentance and amendment of life.
The more he inclined his mind, and drew near to God, in these inward manifestations,
he found that God drew nearer unto him,
so that he had at length thankfully to confess that "`He was found of
Him when he sought not;`" for he felt that it was the free,
unmerited, and unsought goodness of the Lord towards him,
"`the chief of sinners,`" that called him to repentance,
and in time wrought also a reformation of heart;
thus working in him "`both to will and to do,`"
and plucking him as a brand from the burning,
to make him an instrument of honor in His house.

James Parnell states that he was, according to his age,
"`as perfect in sin`" as any in the town where he lived,
and that he exceeded many in the wickedness of his life.
In this state he was loved by the worldly-minded around him, as being one of themselves.
But when the Lord was "`pleased to make known His power in him,
and to turn his heart towards Him,
truly to seek Him,`" the change which was effected by divine grace,
caused him to become a wonder to them, and they hated and turned from him,
in his converted state, as much as they had sought him,
while he was leading an ungodly life.
Even his own relatives,
being in that carnal mind which
"`understands not the things of the Spirit,`"
endeavored to draw him away from faithfulness to God,
and to destroy the work which He had begun in his heart.
And when they could not prevail on him to conform to the world, in its
"`invented fashions, customs, traditions, its ways, fellowship and worship,`"
(for his eye, having being opened by the power of God,
he perceived the idolatry of such things,
and could no longer practice them,)
they became his greatest enemies,
and excited persecution against him,
so that he became "`a mockery in the streets,`"
and was accounted unworthy to live among them,
and some even said, it would be doing God service to kill him.

"`But,`" says this dedicated youth, "`He that called me out from among them,
unto Himself, that I might no longer follow the vain courses of the world,
nor set my delight in things below, but that I might serve Him in newness of life,
that in me His workmanship might appear to the confounding of the heathen,
who knew Him not, He by His power kept me,
and gave me strength to bear His cross and despise the shame;
so that neither fair words nor foul words could cause me to
deny what God by His grace had wrought in my heart.`"
And feeling the preciousness of being brought into spiritual relationship with his
heavenly Father,--feeling the incomparable value of being a son of God,
and if a son, then an heir, an heir of God, and a joint-heir with Christ,
he was made willing, and enabled to come out from among his kindred and acquaintances,
and to "`become a stranger to them who loved not the Truth.`"

The real conversion of his soul,
evidenced by a walk which became the high vocation with which he was called,
had the effect of clearly manifesting the worldly character of the priests,
whose ministry he had been accustomed to attend.
While he lived in the vain conduct of the world, they took no notice of him,
either to reprove or to instruct him;
for they were as deep in the world`'s spirit as others.
Indeed they upheld by their lives and conduct the very
evil which they condemned in their sermons,
and thus disqualified themselves for laboring for the
conversion of the individual members of the flock.
They condemned sin in general, but feared to speak against it in particular cases,
lest they should bring a reflection on their own lives.
But as soon as James Parnell manifested a closer walk with God,
that he was truly and in earnest, on God`'s side,
and as soon as his fruits made manifest that he had been grafted into the true Vine,
and livingly partook of its living sap, then they became his enemies,
and said "`he was deluded.`"
When James Parnell found that the priests were carnal,
and (together with the people who followed them) had only the outward form,
while they denied the life and power of true religion, he separated from them,
and sought a people with whom he might have unity.

George Fox left his relations, and was engaged in his mission in a private way,
as early as 1643;
but it was not till 1648 that he commenced his ministry in an extensively public manner,
at which time he says, "`Various meetings of Friends, in several places,
were gathered together to God`'s teachings, by His light, spirit, and power.`"
The great work which has been mentioned as
progressively going on in James Parnell`'s mind,
and the decisive step of separating himself from the national mode of worship,
took place before he was fifteen years of age, that is, before 1652,
by which time Friends must have been known as a people.
There were, however, no Friends in the place where James Parnell lived,
and up to this time he had had no interaction with any
of those with whom he afterwards united himself,
as to a people, who were gathered to
"`worship God in Spirit, rejoice in Christ Jesus, and have no confidence in the flesh.`"
Indeed, it is clear from his own writings,
that the work was the work of God alone by His Spirit in his heart;
and he forms one among the many instances with
which the early history of our Society abounds,
of those who, without communication with others,
were led by the same Spirit to adopt some of the most important principles of Truth.

It seems probable, that it was in the year 1651, when he was about fourteen years of age,
that he separated from carnal professors,^
footnote:[The word _professor_ is used to refer to anyone who _professed_ faith in Christ.
Here it has nothing to do with teachers or scholars.]
and sought a people with whom he might become united in religious fellowship.
He says, "`there was a people,
with whom I found union a few miles from the town where I lived,
whom the Lord was gathering out of the dark world,
to sit down together and wait upon His name.`"
With these he bore "`the reproach of Christ,`" and was willing for His sake,
to be numbered among those who were regarded as the offscouring of the earth;
but in their afflictions and persecutions for the Savior`'s sake,
they rejoiced in remembering that it was written,
that they who would live godly in Christ Jesus should suffer persecution;
and considered it greater riches to be His people,
and to suffer the hatred and contempt of all,
than to enjoy "`the pleasures of sin for a season.`"
Knowing that they were suffering for His sake,
they felt their confidence fixed on Him alone,
and in His strength were raised above all their trials.

"`About this time,`" says James Parnell, "`I was about fifteen years of age;
and afterwards I was called forth to visit some Friends in the north part of England,
with whom I had union in spirit before I saw their faces.`"
It was probably during this visit to the north, that he went to see George Fox,
who in 1653 was in prison at Carlisle, in whose journal we find it stated,
"`while I was in the dungeon in Carlisle, James Parnell, a little lad,
of about sixteen years of age came to see me and was convinced.`"
From this remark of George Fox, it appears that James Parnell had not, till this time,
had any interaction with Friends,
although the people with whom he had before associated in religious
worship had been brought near to some of their principles.
From what has gone before,
it is evident that James Parnell had already experienced real conversion of heart,
had been brought to see the formality of the priests,
and had separated himself from the customary form of worship to wait on the Lord alone;
so that by this interview with George Fox,
he was merely convinced that the Truth which Fox preached was the same as
that into which he had himself been led by the Spirit of Truth.

George Fox was at this time about thirty-one years of age,
and had been engaged in preaching the Truth about seven years.
It must have been an unspeakable comfort to him, when imprisoned for the Truth`'s sake,
to have received this visit from a "`little lad;`"
to hear from him "`what the Lord had done for his soul,`"
and to trace in his experience fresh evidence of the
substantial reality of those great principles which had been opened to his own mind.
And not less comforting must it have been to James Parnell,
to meet with this father in Israel, and to receive a confirmation of his own faith,
and a deeper conviction of the Truth, by conversation with such an elder.
It is remarkable, however, that he nowhere mentions the name of George Fox at this time.
It is uncertain how long James Parnell stayed with him;
but we find him mentioned as being in his company at Drayton,
where he had a dispute with Nathaniel Stephens and several other priests, in 1654.

James Parnell returned home from the north, and for a time pursued his outward calling,
and was favored to experience the Lord`'s work progressing in him,
and His Truth more and more fully manifested to his soul.
Keeping faithful to the measure of light imparted to him,
through the strength of divine grace, he was soon called to proclaim the Truth to others.
George Fox says, "`the Lord quickly made him a powerful minister of the Word of life,
and many were turned to Christ by him, though he lived not long.`"
At first, he was not sent far from his home in the service of Truth;
and while occasionally engaged in the Lord`'s work,
was still concerned to fill up the intermediate time
with diligent attention to his outward calling.
When between seventeen and eighteen years of age, probably about the middle of 1654,
he was sent to a people about fifteen miles distant,
to whom the Lord was making known His Truth.
He did not know when he left his home that he should have to go further than that place;
but when there, he was moved to go to Cambridge, and from this time,
he was apparently exclusively occupied in the Lord`'s service, either by preaching,
by writing epistles to confirm those who were convinced,
or books against the opponents of Truth,
or by lying in prison for his testimony and faithfulness to the cause of Christ.

He went to Cambridge without knowing what was to be done for him there,
or what he might have to do, and without being acquainted with any in that place,
who would receive him into their houses.
He had heard that the Mayor of Cambridge had caused two
Friends to be whipped for declaring the Truth,^
footnote:[Two women, Mary Fisher and Elizabeth Williams]
as they passed through the town, and not knowing but that a similar portion awaited him,
in obedience to apprehended duty, and without conferring with flesh and blood,
or being intimidated by the rumor of persecution which others had experienced,
he faithfully proceeded on his journey,
and was comforted by the Lord`'s presence and direction.

Having arrived at Cambridge he was gladly received by some,
and learned that there was a Friend in prison for declaring the same testimony,
with which he was himself commissioned.
This did not deter him, however, from publishing, within a fortnight after his arrival,
two papers,
the one "`against the corruption of the magistrates,`" and the
other "`against the corruption of the priests;`" for which he
was committed by William Pickering the mayor,
to prison.
The date of this committal appears from the following remark in
a letter from Richard Hubberthorn to Francis Howgill,
dated 4th of 7th (9th) month, 1654:--"`James Parnell and I are in the dungeon as yet,
where we were put the 28th of this last month; but we feel the mighty power of God,
and are in joy and peace in the Lord: to Him be praise eternal forevermore.`"
James Parnell might have escaped this imprisonment,
if he had been willing to "`give bond for his good behavior;`"
in allusion to which he has remarked:--"`I am redeemed out of
the generation which is guilty of misdemeanors;
and was bound to good behavior by a stronger bond than man can make.`"
He was detained in prison, at Cambridge, for the space of two court sessions,
his enemies not being able to charge him with the breach of any law.
At the second session, a jury was summoned,
and an attempt made to prove the papers which he had published were
"`scandalous and seditious.`"

The jury-men appear to have possessed a more
independent spirit than was common in those days,
when a few individuals often had power to twist laws as they desired,
to act against everything associated with our sense of what is due to our fellow-men,
and to the established laws of the community.
They brought in their verdict, "`that they found nothing, but that the papers were his.`"
His enemies were thus crossed in their intentions of obtaining a legal form,
under the cloak of which they might continue to persecute him.
And although they had so long unjustly detained him in confinement,
they did not immediately liberate him, but re-committed him to prison for three days;
and then sent him out of the town under an escort of men bearing arms and staves,
and with a pass that identified him as "`a rogue.`"
But on the day following, a justice of the peace, coming from Cambridge,
and knowing that he was innocent, "`witnessed the pass to be false, and took it back.`"
Thus James Parnell was set at liberty.
But, notwithstanding the rough usage he had experienced during his first visit,
he soon believed it required of him to return to Cambridge again; where,
and in parts adjoining,
he openly and freely proclaimed the Truth about the space of half a year.
Many gladly received his message; but he says,
"`there were more adversaries; yet Truth spread, and prevailed over its enemies.`"

James Parnell, being young in years and of a "`little stature,`"
and "`lowly in his outward presence and appearance,`"
was denominated "`the quaking boy,`" by the "`envious
professors,`" against whose formality and carnal security he was engaged to testify.
Samuel Cater had been an elder among the Baptists,
but having been convinced of the Truth through James Parnell`'s ministry,
he became affectionately attached to him, and kept with him as much as he possibly could.
Thus he had an opportunity of becoming intimately acquainted with him,
not only as related to his public ministry and doctrine,
but also as to his private character.
He informs us that, notwithstanding his youth and unimpressive appearance,
he was remarkably endowed with divine wisdom,
and "`in the name and power of the living God,`"
was enabled "`to stop the mouths of those,
who came forth in the strength of the power of darkness to oppose the Truth of God,
to catch them in their own snares,
and to confound them in the sight of all who had eyes to see.`"
He had "`a good gift to declare the Truth,`" was full of zeal and
heavenly courage in bearing an unflattering testimony to all,
and was eminently qualified for every service to which he was called,
being enabled to divide the word aright, both by giving instruction to honest,
seeking minds, and by marking out and manifesting deceivers.
He called people to repentance,
and to turn to the light of the Spirit of Truth which visited their hearts,
that through the power of Jesus Christ they might come to experience their souls renewed,
their lives sanctified, and their hearts brought into peace with God.
He exhorted them to come away from the teachings of carnal men,
and from their confidence in the arm and wisdom of flesh, to lean on the strength,
and depend on the teachings of
Jesus Christ alone,--to learn in His Light their own conditions,
and the way to an effectual apprehension of Him as their Savior.
And when any had turned to the Truth, he was earnest in his exhortations to them,
that they might be careful to walk in the Truth to which they had turned,
to watch unto it, to walk in God`'s fear, and to deny themselves; to bear the daily cross,
and to be faithful to that little measure of
light and truth which had been already received,
that thus they might come to know more.

But young James Parnell not only proclaimed good doctrines,
but was also a good example and pattern in life and conduct
by which he preached the Truth, as well as by words.
He was grave, humble, blameless in his conversation, and unspotted from the world;
patient and meek under the sufferings he endured for the sake of Christ;
diligent and willing in the Lord`'s service, even at the jeopardy of his life.
Thus his presence was a strength and comfort to the upright,
but an awe and dread to those who did not walk
answerably to the profession which they made.
"`He was,`" Thomas Bayles has remarked, "`an innocent man,
and lived in the testimonies and the fear of God: he sought nothing here for himself,
but alone labored and travailed,
that the people might be brought unto the knowledge and love of God.`"

[.offset]
The reader will be interested in the following treatise,
selected from James Parnell`'s works;
it appears to have been the first of his publications.
It was written in 1654, when he was seventeen years of age.
It is entitled:

[.embedded-content-document.treatise]
--

[.blurb]
=== A Trial Of Faith: wherein is discovered the ground of the faith of the hypocrites, which perishes; and of the Faith of the Saints, which is founded upon the Everlasting Rock; so that all may see what their faith is, and what they trust to.

Come! try your faith,--all you professors of godliness, of God, and of Christ;
who say God is your Father, and Christ your Redeemer; and that you believe in God,
and are saved through faith in Christ.
Come! search the ground and bottom of your faith, upon what it is built;
for the faith and hope of the hypocrite will perish, (Job 8:13) which stand in words,
and on a weak foundation.

You say, you are saved by the blood of Christ, and by His stripes you are healed;
and so would make Him the ground of your faith.
But from what have you been saved?
and of what are you healed?
Search within, and see.
Christ came to save and redeem sinners from their sins, and to heal them of its wound,
to bruise the serpent`'s head, to bind the strong man and cast him out of His house;
and to open the prison doors, to set at liberty the imprisoned,
and to lead captivity captive; to cast antichrist out of the temple of God,
who sits there as God, and says he is God.
And Christ came to rend that veil of darkness, to open the eyes of the blind,
and to unstop the deaf ears, and to make blind those that can see,
and to make deaf those that can hear; to give strength to the weak,
and to make weak those that are strong; to feed the hungry,
and to famish that which is fed; to make a separation between the precious and the vile,
between the wheat and the tares, the sheep and the goats;
and to purchase for man that which man has lost.
For this end is He come.
And they who can witness this work, can witness Him, and may claim an inheritance in Him,
and have an assurance of their salvation.
Their faith will stand against the beast, and overcome;
for the Lamb shall get the victory.
But they who cannot witness this, cannot witness Christ,
and so are reprobates concerning the faith.

Now, here, all you drunkards are shut out; here, all you swearers are shut out; here,
all you proud and covetous, and lustful ones are shut out; here, all you scoffers,
and scorners, and backbiters, revilers, extortioners, and envious ones,
gamers and sporters are shut out.
And all you self-righteous professors of Christianity
who live in the fashions and customs of the world,
delighting in the pleasures and vanities of the world, and having fellowship with it,
whose citizenship is among the children of the world--you are shut out.
You who cleanse only the outside of the cup,
while the inside is full of lust and filthiness, pride, covetousness,
and all uncleanness; white-washed walls and painted sepulchers are you,
who deceive the carnal eye and ear--but the Lord searches the heart.
You are all shut out of the true faith, which "`purifies the heart.`"
(Acts 15:9). The serpent is head in you, and your strong man keeps the house,
and a stronger than he is not yet come; but antichrist sits in the kingdom,
and reigns as an "`angel of light.`"
Indeed, the wound of sin is yet fresh--the veil of darkness is spread over you,
and death reigns.

Alas!
Christ lies low in the manger, and the inn of your heart is taken up with other guests.
And here, you can make no claim to the blood of Christ;
you have nothing to do but to talk of God and Christ,
and have no right assurance of your salvation.
Your faith is vain, and your hope vain; and the foundation thereof is sandy,
and it will not stand in the day of trial, but will be as a broken reed to lean upon.
Here all your prayers and praises, singing, grace, baptism and sacraments,
upon which you build your faith, and think to merit, are all in vain,
being offered up from an unclean heart.
For how can your hearts be clean while you live in sin?
For sin lodges in your hearts; and while sin is there, purity cannot dwell there;
nothing that is pure can come forth from an unclean vessel;
God does not put His treasure in an unclean vessel.
He is pure and receives nothing that is impure.

Here all your faith is shown to be vain;
for you destroy your faith with the words from your own mouths,
who say you believe you shall never overcome sin so long as you are in this world,
and that you shall never be made free from sin.
And here you show that your faith is not built upon Christ,
who came to destroy the works of the devil and to cleanse from all sin.
But those whose faith was built upon Him did witness this, and said,
"`The blood of Christ has cleansed us from all sin,`" and "`they that
are Christ`'s have crucified the flesh with its affections and lusts`"
which are the ground of sin,
and "`he that believes is born of God;
and he that is born of God cannot commit sin,`" etc.
So now, what right assurance have you of your salvation?
Or upon what is your faith built, when both Christ and the Scriptures testify against you?
Faith, which is not built on the Rock, Christ Jesus, is vain, and perishes;
and he who has the true hope in him, "`purifies himself, even as He is pure.`"
Here your faith is searched, tried and proved, and is found all vain and perishing;
and so is not built upon the Rock which perishes not.

Therefore, come down, all you high-minded pharisees!
Lay aside all your professions; throw down all your old building,
and begin and lay a new foundation.
For the higher the pharisee climbs, the greater will be his fall.
He that will be wise must first become a fool; for man by his own wisdom knows not God.
Therefore the pharisee, who stands in his own wisdom,
is shut out from the saving knowledge of God.

And all you willfully blind, carnal, ignorant creatures, whom my soul pities,
when I see how ignorantly you are led,
who pin your faith on the sleeves of your forefathers,
and live in lightness and carelessness, spending your youth in vanity, in gaming,
pleasure and sporting; in drunkenness, swearing, and lying;
in vain talk and foolish jesting; in pride, lust and filthiness; and say,
you follow your forefathers;
and that your pleasures are mere "`pastime and recreation;`" and your
vain talk and foolish jesting is only "`pastime and merriment.`"
So you pass your time away, and say your drinking, and rioting, and feasting,
are "`good fellowship and neighborhood;`"--so you cover your sins and iniquities.

But, woe unto him that hides his sin, and covers his iniquity!
All this will profit you nothing, nor can your forefathers excuse you before the Lord.
For in the beginning Eve could not justify Adam, nor excuse him;
but he was condemned because he hearkened to her voice, and disobeyed the Lord.
Thus Adam suffered for his own sin,
and so did Eve for her`'s. And so it will be no excuse for you
in the day of account to say you followed your forefathers,
and did as they did before you.
For then will the Lord say, "`Because you followed the traditions and fashions,
the customs and inventions of men, and have hearkened to the voice of the serpent,
and have disobeyed My voice and command, and slighted My counsel,
and desired none of My reproof; but cast My law behind your backs,
and trampled My mercy under foot, and have turned My grace into wantonness,
and have spent My creation upon your lusts; and have stoned, stocked, buffeted,
imprisoned, and shamefully intreated My messenger,
which I sent unto you to forewarn you of your iniquity,
and have crucified My Son in your hearts--therefore, Depart from me,
you workers of iniquity, (I know you not!) into everlasting torment,
prepared for the devil and his angels.`"
See now how vain your hope is, and how weak is your faith,
when you have more assurance of your damnation, than of your salvation.
For the Lord says, "`No unrighteous person can enter His kingdom, nor any unholy,
unclean thing.`"

Therefore, all you who desire the salvation of your souls,
try and prove your faith and hope, in which you trust;
and take heed of trusting in a broken reed, lest it deceive you.
Experience has taught you that if the foundation
of a building is decayed and wasted and naught,
the building will fall when a storm comes.
"`Let him, therefore, that thinks he stands, take heed lest he fall.`"
And all of you, whose desire is after righteousness,
hearken unto that Witness in your consciences, who raises up desires after righteousness,
and who shows you the vanity of your lives, checks you when you do amiss,
and troubles and torments you in conscience when you have done any evil act.
Be willing to be guided by this, and it will lead you to repentance and newness of life,
and to forsake those things which it discovers to be contrary to the will of God.
And if you are willing to follow this Witness, and to be guided by it,
you will find a Teacher continually present,
checking you in your conscience for vain thoughts, and for vain, and idle,
and needless words and actions;
and it will also crucify the lust which is the ground of these things.
It will lead you out of the paths of death, into the way of life; out of the traditions,
customs, fashions and opinions of the world, into the assurance of the Eternal Truth.

And you, who are willing to follow this Light, and to be guided by it,
shall need no man to teach you; but it will be a Teacher unto you,
teaching and directing you in righteousness, purity, and holiness.
And if you are diligent, keeping your mind within, with an ear open to the pure Voice,
you shall find it present with you wheresoever you are,--in the fields, in your bed,
in markets, in company, or wheresoever you are.
When your outward priest or teacher is absent or far off, it will be present with you,
and will check you and condemn you for that which no outward eye can see,
and will cleanse your heart from lust, and deceit, and uncleanness,
and will purify your heart, and make it a fit temple for the Pure One to dwell in.
And then your sacrifices will be pure, which come from a pure heart,
and the Lord will accept them.

But, if you would attain to this, you must be willing to deny your lusts, your vanity,
your delights, and whatever has been your life; for Christ has declared,
"`whosoever will save his life, shall lose it;
and whosoever will lose his life for My sake, shall find it.`"
So, there is no obtaining life, but through death; no obtaining the crown,
but through the cross.
Therefore you must deny yourself, and take up your daily cross, and follow Christ,
if you would be His disciple.
You must give up yourself wholly to be guided by the will of God,
so that all which is contrary to the will of God may be crucified and forsaken,
(though it be ever so near or dear to you)--whether lands or living, wife or children,
friends and acquaintances, or all the world, and all delights in the world.
For the Lord has said, "`He that loves anything more than me, is not worthy of me.`"

So, may the Lord God Almighty prosper all the tender desires which are raised up towards Him,
and feed the hungry and thirsty souls, as He has promised,
and raise up His own into dominion in all His children, that He alone may be glorified,
praised, and honored, who is worthy, and to whom all belongs.

And this is the desire of his soul, who is a servant of the Lord, who is hated, reviled,
and derided by the world, because he has no fellowship with it, nor with its vanities,
but rather testifies against its ways, fashions, traditions, customs, fellowship, words,
and worship; and sees them all to be formal imitation, and the invention of men,
out of the Covenant of God, and therefore cannot but deny them;
and for this cause he is hated by all, both priest and people:
whose name according to the world, is

[.signed-section-signature]
James Parnell

--

[.offset]
The following extracts from his works, will enable us to form some idea of his ministry,
and of the seriousness of his dealing with carnal professors of Christianity,
about whom he thus expressed himself:

[.embedded-content-document]
--

"`But, praised be the Almighty, who has so weakened their hands,
and shattered their foundation, and caused His light to shine out of darkness,
that they are so manifest, that all you people who love light better than darkness
may now see how ignorantly and blindly you have been led,
as strangers from the Father of light, after the vain traditions, customs, forms,
ordinances, and imaginations of men, with a vain profession and feigned faith.
You have laid hold of notions, but still live in your sins and iniquities,
still alive in the first nature, under death`'s dominion,
still strangers from the God of life, and from Christ,
the Savior and Redeemer of His people from their sins.
Thus you lie under the power of darkness, and delusion of antichrist,
both priests and people--for like people, like priest, and so says the prophet,
that your leaders cause you to err by their lies and their lightness.

And though you are full of teachers, yet you are lost for lack of true knowledge,
and are still led captive in your sins and iniquities, following those who have the form,
but deny the life and power, who are "`ever learning,
but never coming to the knowledge of the Truth.`"
You differ from the heathen in name or profession, judgment or opinion,
but are still alive in the same nature, in the fall, under the curse,
and are children of disobedience, in whom the prince of darkness rules.
And you must have a law outside of you to keep you in awe and fear,
as they have whom you account heathen; but the righteous need no outward law,
"`because the Law was added because of transgression.`"
And you are fighting, and killing, and devouring one another,
as they do whom you call heathen; and you are drunkards, and swearers, and liars,
as they are.
You are scorners, and scoffers, and revilers, and backbiters, and proud, and covetous,
idolaters, and high-minded oppressors, as they are, both priest and people.
You are idolaters, as they are, eating and drinking, and rising up to play;
and you are envious and malicious, suing, and rending,
and tearing one another at the law, both priest and people,
pulling down others to set up yourselves.
You are cheating and defrauding one another of the earth, which is not your own;
and you are persecutors and strikers and stoners of the
innocent children and servants and messengers of God.
Indeed, what sin is there among those whom you account heathen, that is not among you,
and does not abound?
Yes, those whom you call heathen, may condemn you in much of your practice.
Oh! be ashamed and blush, you priests and teachers of England,
to see your ministry and the fruits of your ministry so laid open before you.
And thus you are manifested to be those who come
near the Lord with their lips and mouths,
but their hearts are in the earth, far from Him; otherwise you would walk more uprightly.
"`But,`" says the Lord, "`in vain do you worship me,
teaching for doctrine the commandments of men.`"

And these things,
both Christ and His Apostles judged and condemned as being out of the new covenant;
for here no unrighteous person can dwell; and here, all wars are ended,
and '`the swords beat into plow-shares, and the spears into pruning-hooks.`'
Here, in the new covenant, there is no oppression, nor self-exaltation,
but he that would be greatest, must be least.
Yes, in righteousness are they established, and they are far from oppression,
and the Lord alone is their Teacher.
And here there is no need of an outward law, for to them there is "`no condemnation,
who walk not after the flesh, but after the Spirit.`"
And here there is no respect of persons, but all are members of one body,
of which Christ is the Head, and they serve one another in love.
Here is the new covenant, and the children of the new covenant,
who are washed and made clean by the Blood of the new covenant;
but you are aliens and strangers from this covenant,
who are living in mere notions and outward professions.

--

[.offset]
In the same work Parnell thus describes the true Church:--

[.embedded-content-document.treatise]
--

And concerning the Church, it is now being gathered and redeemed, not by the will of man,
nor by the wisdom of man, but by the will and power and Spirit of God, which,
according to His promise,
He has poured upon His sons and daughters now in these latter days.
And by this Spirit we are carried abroad in the power of the Almighty,
to declare His powerful Truth,
which the Lord has decreed shall prevail upon the hearts of the people,
which is glad tidings of great joy unto them that receive it;
but unto the stubborn and stiff-necked, and rebellious, it is tidings of woe and misery.

And though the messengers of the Gospel are by some rejected, reviled, reproached,
scoffed and scorned, stocked, stoned and imprisoned, despitefully used,
slandered and abused; yet, nevertheless, blessed be the name of the Lord,
there are some found worthy, who receive with much joy the messengers of the Gospel.
These know how beautiful are the feet of those that bring glad tidings,
to the reviving the just Witness for God within,
and the raising up of the dead spirit to life,
so that the living come to know and praise the Lord.
In this way the Righteous One comes to reign, and the wicked one comes to be judged,
and the mind comes to be turned from darkness to light.
It is to this Witness of God in every creature that we preach,
and by it we are made manifest--both from where we come and the testimony we declare.

But to those who do not receive it, we are not known;
and are therefore by them esteemed deceivers and deluders, vagabonds, wanderers,
and the like.
Yet at all this we do not wonder at; for we read,
"`the servant is not greater than his Lord;
for if they have called the Master of the house Beelzebub,
how much more those of His household?`"--and,
"`if they had known Him, they would not have crucified the Lord of glory.`"
Even so, there is a Witness in every conscience, both in them that believe,
and in them that perish, unto which we do clear our conscience,
and leave all without excuse.
Indeed, this Witness will answer for us in the mighty day of judgment,
though it will be the condemnation of all those who have hated it.

But, as many as receive this divine light,
to them He gives power to become the sons of God.
Those who are led and guided by the one Spirit of Truth,
which the world cannot receive (even the Comforter,
of whom you have heard that He should come) are by Him separated out of the world,
and redeemed out of the rudiments and pollutions thereof--its fashions, its customs,
its words, its ways, its manners, its breeding, its fellowship, love and friendship,
its honor, its glory and its worship.
So they become strangers to the world, and so they are hated of the world,
because they are not of the world.
Truly the enmity stands between the two seeds; for while these were of this world,
the world loved them; but now that they are gathered out of the world,
and separated from the world, and testify against it (both in their words and actions),
therefore the enmity rises up in the world against the righteous Seed in them.

These are they upon whom the end of the world has come,
and to whom it has been given to know the mysteries of the kingdom;
but to the world they are given in parables.
And these are they who have come with a mighty
arm and power to turn the world upside down,
whom the Lord has gathered and is gathering out of the world,
by His own Spirit of truth and love, to walk in the way of truth,
even the highway of holiness, where the ransomed of the Lord walk,
and serve and worship Him in Spirit and in truth.
Such as these the Father is seeking to worship Him, in whom He is doing His own work,
even to destroy the old creation,
and to "`create new heavens and a new earth,`" wherein righteousness dwells.
And these are the new creatures, in whom the new work is witnessed,
in whom the Father has manifested His Son, that He might condemn sin,
bind the strong man, cast him out of His house, spoil his goods,
and so "`destroy the works of the devil,`" and cut down that man of sin--
even that son of perdition who is exalted above all that is called God,
sitting in the temple of God, and saying he is God.
This is he by whom the world is deceived, who is the god of this world,
even the prince of darkness who rules in all the children of disobedience.
John, speaking in the Light,
says "`the whole world lies in wickedness;`" and so Christ
comes with a sword to make war with the wicked one,
and to cast him into outer darkness, and so take his kingdom from him,
and rule Himself in righteousness.

He is King of Saints, who is come to redeem unto Himself a pure people,
and to wash and cleanse them from their sins by His blood,
and so wash away all filthiness, both of flesh and spirit.
And this is the true baptism by which they are received into His church and faith;
and here is the effect of His blood wrought in man.
Indeed, He does and will continue to manifest His mighty power to purify, cleanse,
and make man a fit temple for Himself to dwell in.

Thus Emmanuel--"`God with us`"-- is made manifest,
and the saints`' bodies are made the temples of the Holy Spirit.
And thus the Word of life and reconciliation is witnessed raising up the soul into life,
and reconciling it to God.
These are they that are begotten and born again of the immortal "`Word,
which lives and abides forever;`" and here is the household of God,
the household of faith, and the household of love,
who speak the things which they have heard, seen, and tasted of the good Word of life,
who was in the beginning.
These are the children of light, who are gathered out of the dark forms, judgments,
and opinions, into the life and power of godliness, to walk in the light of life,
wherein they are gathered and united by the one Spirit of love and life into one body,
of which Christ is the Head.
Here is the true Church, which the Lord is gathering, and washing, and cleansing,
and purifying by His Spirit, that He may redeem unto Himself a pure bride,
not having spot or wrinkle, or any such thing,
whose insides are washed and made clean through the Word,
by which they are reconciled into the love and union, which spring from the life of God.
And here is the Vine and the branches, and the communion of the Church,
all feeding upon one Bread, and drinking of one Cup.
Yes, this is Christ, the life of the saints,
and as many as are baptized into this Church, partake of this communion.
These are they who have denied themselves, and have borne the cross of Christ,
by which they are crucified unto the world, and the world unto them,
who are gathered into one covenant of life,
where all are fellow servants under one Master,
who serve one another in love and meekness.
Here is the true humility wrought in the heart,
the true washing of the feet without hypocrisy.

And thus is the church of Christ gathered by one Spirit,
and by the same it is circumcised, and baptized into one life, light, and power,
where all dwell as members of one body, of which Christ is the Head.
Here is the blessed union and communion in one,
and here God is worshipped "`in spirit and in truth.`"
And as Christ is spiritual, so is His church, which is His body,
and so are His ordinances.
Here are the true Christians, not those who have the notion of these things,
but they that witness and possess them in the life.
"`They that believe, have the witness in themselves.`"
They that believe, have passed from death into life;
and "`the life they now live is by faith in the Son of God.`"
These are new creatures, who are "`in Christ Jesus,`" to whom there is no condemnation,
who walk not after the flesh, but after the Spirit.

Against such as these there is no law,
for they are translated out of that nature for which the law was added;
and are set free by "`the law of the Spirit of life,`" and are
"`made partakers of the divine nature`" of Christ,
by which they are made Christians.
And such now witness the effect of the blood of Christ wrought within them,
and the end of His coming, and the benefit of His death, who are dead with Him,
and risen through the death of the cross.
Yes, these are they who have escaped the pollutions of the world through
the knowledge of the Son of God within them--Christ within,
the hope of glory, or else there is no hope of glory!
For they who cannot witness Him so, are still in the reprobation,
as the apostle says (2 Cor. 13:5). And here is the Son in the saints,
and the Father in the Son, and thus all are made perfect in one.
And here is the true Church, where there is one Teacher, one Lord, one faith,
one baptism, one light, one life, and one way, one Shepherd and one sheepfold,
and one Priest over the household of God.
Here is one hope, and one language, one family, one God and Father of all.`"

--

[.offset]
This was written in 1655,
when James Parnell was between seventeen and eighteen years of age.

While traveling in the work of the ministry,
he sometimes held public disputes with the different religious professors of the day,
who, although under ordinary circumstances were bitter enemies to each other,
they nevertheless ardently and cordially united
to oppose that pure and spiritual worship,
that sanctity of life, and that reality in religious experience,
which James Parnell was given to proclaim.

On the 30th of the 3rd month, 1655,
while James Parnell "`was freely declaring the Truth of God,`" in a house at Fenstanton,
in Huntingdonshire, several baptists with their teacher, Richard Elligood,
entered the room.
After a time the teacher arose, and addressed James Parnell:

"`Sir, if you please I will speak something to what you have said.`"

James Parnell replied: "`Here there is no need of compliments.`"

The teacher continued, "`You have said that God does not respect any forms,
and yet you used the form, and so used that which God has no respect to.`"
And being asked what form had been used, the teacher replied, "`The written letter.`"

To which James Parnell answered,
"`He that uses the written letter to talk of it _without the life and power,_
sets up a form, and makes a form.`"

This answer satisfied the people, but the teacher continued to dispute.

So James Parnell said, "`A form is this--the likeness of a thing,
but not the thing itself; such as those who have the likeness of a church,
with their elders, pastors, and teachers, but not the Church itself.
In the same way many imitate the Scriptures,
but live not in the life of Him that spoke forth the Scriptures,
and so lack life and power.
These are the formalists, who make forms and likenesses to deceive the simple,
even as the devil may take the form of '`an angel of
light,`' but he has not the light and power itself.
And it is he who appears to rule in the formalists and self-actors today;
but the Day of the Lord does make him manifest, and therefore he rages.`"

On several occasions when James Parnell returned to Cambridge, he heard it reported that,
when he was absent, the Baptists boasted of intending to have a dispute with him.
After some preliminary difficulties in coming to a mutual
understanding as to the mode and regulations of the dispute,
the 20th of 4th Month, 1655, was appointed.
When they arrived at the place provided by the Baptists,
they were not allowed to meet there.
They then went to the house of one of the Baptist party,
where the woman of the house behaved in a very unchristian manner towards Friends;
which led James Parnell to remark that,
she "`had clearly not departed from the old nature,`" and it was evident,
she had derived no benefit from her water-baptism.
James Parnell then retired to a Friend`'s house,
amid a great rabble of rude students and people, to whom he declared the Truth.

After a time, a message came that the Baptists were in the Shire-house,
in the castle yard, and had sent for him.
Here James Parnell found a man named Doughty, a Baptist, and Rix, an Independent,
two great enemies to each other on ordinary occasions, now united against him.
But after all the trouble in determining how they should meet,
and the difficulty in getting a place, only one question was asked,
and only one answer given by James Parnell, which satisfied some, but not all.
James Parnell, however, had an opportunity of speaking to the people,
and proving to them that the charges brought against the Truth,
and against himself as its messenger, were groundless.
Many rude students were present on this occasion, and having plotted together,
as soon as James Parnell left the castle yard,
they flocked together about him and treated him very shamefully.

In the month following,
while several of the Lord`'s people were met together in a Friend`'s orchard,
at Littleport, on the Isle of Ely, John Ray, with two other teachers,
came among them to "`excommunicate`" Samuel and Ezekiel Cater,
who had formerly been elders among the Baptists, but,
having been convinced of the Truth by James Parnell`'s ministry,
had united themselves with Friends.
John Ray,
"`having run out into many disorderly words,`" excused
himself from staying to prove his assertions,
saying, "`he must be at the Steeple-house^
footnote:["`Steeple-house`" was the term early
Friend`'s used to refer to church buildings.]
shortly.`"
When their meeting was over, James Parnell passed into the town, and,
having been informed that John Ray was railing against the Truth in the Steeple-house,
he went there with some Friends.
When the sermon was ended, James Parnell stood up,
and claimed the order of the true Church from 1 Corinthians 14:26-30,
that "`all might speak, one by one, and if anything be revealed to him that stands by,
let the first hold his peace.`"
John Ray refused to stay and defend his statements,
although many of his congregation wished to detain him.
James Parnell afterwards addressed the people in the graveyard.

[.offset]
+++[+++The conduct of James Parnell here is worthy of notice.
Although John Ray had disturbed the meeting of Friends on the same day,
Parnell quietly waited till the service was ended, and,
then claimed the order of the True Church, as laid down by the Apostle.
He manifested a similar disposition to maintain right order on an occasion,
just mentioned, refusing to speak in the Shire-house,
till the jailer had given permission.
Another instance will appear shortly.]

On the following day, this same Ray told a friend that James Parnell had said,
"`he was head of the true Church.`"
This led him with several Friends,
to attend a meeting which the Baptists were holding in a house,
where they found John Ray speaking to the people.
As soon as he saw James Parnell, he ceased speaking, closed his book, and bade him,
"`Be gone out of the house.`"
Parnell answered, "`Is your spirit limited? Is your spirit bound?`"
He again told him to be gone; and asked him, why he disturbed them?
James Parnell inquired how he had disturbed them, "`was I not silent until spoken to?`"
It being an open meeting, although in a private house,
James Parnell did not consider himself bound to leave,
(although John Ray manifested great anger,
and one of the elders pushed Parnell on the breast with his hands several times.)
Having told John Ray that he was ashamed of his doctrine,
"`he shook off the dust of his feet for a testimony against them, and so left them.`"

However severely James Parnell might have, at times,
addressed those whom he regarded as living at ease in their sins,
or as deceiving themselves and others by a profession without a possession of the Truth,
or as false teachers causing the people to err by
teaching them for doctrines the traditions of men,
yet it appears clear from the testimonies of those who
were acquainted with his private character,
that he was meek, gentle and patient, and his addresses to both those who were convinced,
and at times to those who were still in darkness, evinced a kind and affectionate mind.
His only object in using severity,
was to arouse men to a sense of the seriousness of their
conditions if they remained in an unrepentant state.
He had "`known the terrors of the Lord,`" and therefore was earnestly
concerned to call others "`to flee from the wrath to come.`"
And as he knew the sweet consolations of Jesus Christ,
he was therefore eminently qualified to invite the truly thirsting soul to
come and drink of the same living Fountain of spiritual refreshment.
He was without doubt,
"`an able minister of the Gospel,`" and left many seals of his ministry.
In that day,
it was remarkably verified that out of the mouths of
babes and sucklings praise was ordained,
and the weak things were chosen to confound the mighty.

Samuel Tuke remarks in his memoir of Stephen Crisp -- "`The
Society of Friends in the counties of Cambridge,
Essex, Suffolk and Norfolk, was first raised and became very numerous,
principally through the labors of three instruments, James Parnell, William Caton,
and George Whitehead, neither of whom had attained the age of twenty years.`"

The following original letter of Parnell,
in the possession of the Meeting for Sufferings, addressed to Edward Burrough,
and Francis Howgill, may be inserted in this place.
It is dated "`18th day of 5th month.`"
There can be no doubt, that it was written in 1655.
It presents many points of interest:

[.embedded-content-document.letter]
--

[.salutation]
Dear friends and brethren,

In the eternal, unchangeable love and life of the new covenant I am with you,
and there do I salute you, where we are one, in our measures,
though ten thousand--all children of one Father, brethren and sisters of one family,
and heirs of the promise, everyone in the measure of the gift of grace given unto us.
Herein does our joy abound, and is made full in one another.
In the Light of the new covenant you can read me, where I am present with you,
and do embrace and salute you, though absent in body.
For we are all begotten by one Immortal Word, and so are born again,
and come to bear the one image of our Father,
so that hereby we may know one another to be the children of one Father, and do see,
and read, and enjoy one another in this same unchangeable covenant of love and light.
Here is the blessed union and communion and fellowship,
and the glorious liberty of the children of the new covenant,
who are sealed in this everlasting covenant of life.
And this is the great riches of the love of God bestowed upon us,
that we should be found worthy of this high calling.

Dear brethren, the letter which you sent from Cambridge I received,
with the same love that sent it,
and I did acknowledge it as an evidence of your care and wisdom.
Shortly after I went to the Isle of Ely, and I had meetings at Ely town,
and was moved to go to the Steeple-house,
but the rude people would not allow me to speak.
Yet I was mightily preserved by the power of God,
and I had a great meeting in the town that day,
and in much power was I carried forth to the binding and chaining of the heathen,
and the raising up of the Witness in hearts, so that many were convinced.
The town is much hardened against the Truth,
but yet I see a further work to be done in it.
There is a good people coming on at Littleport, in the Isle.
I remained there a time among them,
and there are about sixty that are brought to meet together in that town alone.

On the first day I had a meeting at Soham,
within three miles of Colonel Russell`'s. There I was moved to go to the Steeple-house,
were a London priest got up into the seat of the Pharisee; and he was a true Pharisee,
for he was much painted.^
footnote:[Quakers used the word "`painted`" in the same
way the Christ spoke of painted or whitewashed tombs,
which "`appear beautiful outwardly,
but inside are full of dead men`'s bones and all uncleanness.`"]
I was permitted to stay until he was done;
and then I was carried out in mighty power to speak to him and to the people,
which bound them all under.
They were a great people and very rude,
but the power of God was wonderfully seen in delivering me,
so that I do not think that they gave me a single stroke.
The throng was great, so I pressed forth into the yard, and there they made way for me,
and I was moved to speak in much power, and they stood still like lambs about me.
At length there came one Robert Hammond, called a justice,
who had been at the Steeple-house,
and said there was a proclamation that all who disturbed
the ministers in the time of their public exercise,
should be apprehended as disturbers of the peace, so, if I would not pass away, he said,
I should be apprehended.
I felt free to pass on from that place,
but I told him and the people that I should declare the Truth in the town that day.
And so upon these conditions, I was set free.
I had a great meeting in the town that day,
and there were present several of the people who belonged to the group at Chippenham.
Those that were there received the Truth willingly,
and there were many people convinced that day.

The news of this meeting reached Hammond`'s ears,
and stirred up his spirit against the Truth.
The priests and he consulted together against me, and the next morning,
he sent a warrant for me, and committed me to Cambridge jail for disturbing the priest,
whereas he had before set me free from that charge, in the presence of a hundred people.
So this was on the last second day, that I was sent to Cambridge,
and there I was put into the low jail among the thieves.
But the next day Justice Blackeley sent his warrant and set me free from the bonds;
though I was made very willing to remain if it had been the Lord`'s will.
But in His great wisdom He ordered it according to His good will and pleasure,
for I did not mention it to Blackeley, but he did it of his own accord.

The next day I went to a meeting six miles from Cambridge,
where I met with my dear sisters, Ann Blakely and Dorothy Waugh.
They will remain in these parts a while.
My sudden release and going into the country proved very serviceable,
for the opposers were much exalted and had rejoiced at my imprisonment.
It is likely, if the Lord wills,
I shall pass shortly back into those parts where I was taken,
for there is a people there to be brought forth.
But the opposers, I perceive, are plotting together to get me into prison again,
for the jailer has been with Blackeley about it,
and is troubled because he let me go without bail,
and threatens to get another warrant for me.
But I am content, whether in bonds or out of bonds.
I have thought to remain hereabouts for a time, if you have movings to write anything.

Salute me dearly to my dear brother George Fox, and all the rest of my dear brethren,
sisters, and fellow-laborers in the vineyard of the Lord.
Salute me dearly to all my dear and tender hearts,
whom the Lord has chosen out of that great city, Sodom, to bear His image,
and to glorify His name, and to be as signs and wonders in an adulterous generation.
The Lord God prosper, and increase His glorious work in them and among them,
with a strong arm, and power to beat down their enemies before them.`"

[.signed-section-signature]
James Parnell

[.signed-section-context-close]
This from Cambridge, 18th of 5th Month.

"`I shall be glad to hear from George, or from any of you.`"

--

[.offset]
It seems worthwhile to insert in this place, the following extract,
which forms the conclusion of one of James Parnell`'s works, entitled,
"`A Shield of the Truth,`" in which he briefly states some of the accusations,
brought against Friends, and replies to them, frequently with remarkable clearness:

[.embedded-content-document.treatise]
--

"`And now something to all you tender-hearted ones,
who are convinced by the Light of God in your consciences,
which makes your consciences tender.
For your sakes I have laid myself open freely,
and so I desire that you may mind that Light of God in your hearts (to which I speak,
which is my Witness, and which has convinced you), that it may be your true guide,
which will lead you into conversion into the Life,
and to witness with me against the world, that my labor may not be in vain.

Look not out at scandals, false accusations, and reports,
for these are the reward which the righteous have always received from the world.
Christ, our Lord and Captain, showed the example, as it is written,
"`they who will live godly in Christ Jesus must suffer
persecution;`" and "`they who depart from iniquity,
make themselves a prey.`"
That in you which cannot bear these things is not of God.
So turn your minds inward to that measure of Light in you, which is without guile,
which is gentle, which can bear all, as it did both in prophets and apostles,
and all the holy men of God.
This led them through good report and evil report, through persecution and through death.
And this is the way to life, and he who enters must enter this way.
So fear not, but be willing to give up and to part with all,
though it be ever so near and dear, yes,
though it be your bosom friend and cherished possessions:
"`For he that love anything more than Me, is not worthy of Me,`" says the precious Pearl.
And "`He that will not leave all and follow Me,
is not worthy of Me.`" Moses thought it greater riches
to suffer affliction with the people of God,
than to enjoy the pleasures of Pharaoh`'s court for a season.
For the pleasures of this world, and the afflictions of this world,
endure but a time and then pass away.
All things visible pass away, but the joy of the righteous endures forever;
and if our hopes were only in this life, we were of all men most miserable;
but he that endures to the end shall have a crown of glory, as Paul witnessed.

So, "`fear not little flock;`" but be faithful, valiant, and bold,
"`for it is your Father`'s good pleasure to give you the kingdom;`"
and a hundred-fold shall you receive of what you lose,
whether lands or livings, wife or children, or whatsoever it be.
The promise is to the faithful,
and your joy and advancement shall be in the destruction of your inward enemies,
when the Lord shall make your enemies your footstool.
But this is witnessed through the warfare,
and he who endures to the end of the war shall witness it.
This, in my measure, I witness;
and out of tender love from my soul to your souls do I declare it,
and desire that you may all endure to witness with me.
For love is charity, and the Light leads through all.
So I rest in my habitation, known to all that can read me in Spirit.
Farewell,

[.signed-section-signature]
James Parnell

--

[.offset]
The following paper, written in 1655, will be read with interest,
especially when we consider the youth of the author:

[.embedded-content-document.paper]
--

A word to all, who are still in your own formings, self-actings, and imitatings.

You are acting in that nature which is "`enmity against God,`" which is
"`not subject to the law of God, neither can be.`"
So all your formings and actings are in vain, for they are not from life,
but from death instead of life.
But there is a life that comes from death,
for in the destruction of death life is obtained.
Therefore,
to the Light of the Lord Jesus in all your consciences (which
Light is the Witness for God) take heed,
to which I speak in you all, which witnesses for God against the secrets of your hearts,
and reproves you in secret for all actions and deeds of darkness.
Indeed, this Light will search you through,
and let you see what you have truly witnessed of the work of God in your hearts,
for all your long and great profession of faith in Christ,
esteeming yourselves to be saints in Christ and members of His church.
And in this Light you will see if you have truly
witnessed the earth being removed out of its place,
and the mountains removed by the eye of faith, and the veil of darkness rent.

Is not the first man still standing in you?
Are you not in the first image, where the serpent is head?
For while you are strangers to the Light, and your minds are turned from the Light,
you are wandering and straying in the paths of darkness,
and so you are the children of darkness,
in whom the prince of darkness rules--even the serpent, who is head in the carnal man.
But the promise is, "`The seed of the woman shall bruise the serpent`'s head.`"
But while you are acting in your own wills and wisdom, the serpent is your head,
and you have not yet come to witness this first promise fulfilled,
but are still in the fall, under the power of darkness, in the disobedience,
and strangers to the cross.
These, who are in that nature, have no part in Christ.
For none come to have a right in Christ except through the cross;
for as many as are baptized into Christ are baptized into His death;
and they that are dead with Him, do live with Him.
They that are in Christ are new creatures; old things are passed away,
and all things are become new.
But they that are not in Christ, are still in old Adam, and so in the fall,
under the curse, and under death`'s dominion,
driven out from the presence of God into the earth, where death reigns over all,
from Adam until Moses, regardless of what you profess.

Therefore, read yourselves by the light which comes from Jesus Christ,
and shines into your dark hearts, that which searches the heart and tries the reins,
and makes manifest all secrets.
All who have a desire to find the way of Truth, I direct your minds unto this light,
turning you from the darkness to the light,
that thereby you may come to see how you have wandered
and been scattered in the many ways of darkness,
in the land of darkness, in the cloudy and dark day, as sheep without a shepherd,
being carried about after the voice of strangers, away from the Shepherd of your souls.
Therefore, hearken no more to those who cry,
"`Lo, here,`" or "`Lo, there is Christ,`"
who seek to draw your minds without, to seek for a Christ without,
and a redemption without, and a sanctification without, and a righteousness without,
and a God without.
But turn your mind within; for the kingdom is to be found within, if ever you find it.
For there is no way to come unto the true knowledge of the truth, or of God,
or of Christ, but by that gift of God within;
for "`that which may be known of God is manifest within.`" (Rom. 1:19)

The way to God is to be found within by the Light, which manifests and slays death.
"`The spirit of man is the candle of the Lord,`"
and Christ`'s "`life is the light of men.`"
So turn in your minds to the light of the Lord Jesus, which, if you love it,
and bring your deeds to it,
will let you see the deeds of darkness and the paths of death.
And it will also search your hearts, and make manifest your inward parts,
and let you see what you have lost.
And as you love this light,
and like to "`retain it in your minds`" and to be guided by it,
it will lead you out of all the crooked and adverse ways of darkness,
into the light of life.
So you will find and know the voice of the true Shepherd, who is come to seek out,
and gather all His scattered sheep from among the mountains and valleys,
and the many ways and crooked paths, wherein they have wandered,
and to gather them together into one flock, into one way, into one sheepfold,
where He alone will be their Shepherd.

And as you love the light, and follow it,
you will see how it will lead you out of your many forms and many ways, into one way.
It will lead out of your own wisdom and imaginations,
wherein you have been building Babel,
and it will strip you of all your own righteousness,
wherewith you have covered over your deceitful hearts; yes,
it will lay your deceits before you, and bring you to judgment.
And if you love this light and follow it,
and are willing to wait upon it (outside of your own wills, wisdom, imaginations,
carnal thoughts, reasonings, consultations, self-acting and imitating),
it will lead you to distinguish the voice of the true Shepherd within you,
from the voice of the stranger, and so to know the precious from the vile.

He who said, "`I am the Light,`" said,
"`I am the good Shepherd,`" and He will bring
you to know the way and door into the sheepfold,
if you do not run out in your own wills,
and seek to climb up another way--for the way is but one.
He that said, "`I am the Light,`" said,
"`I am the way,`" and "`I am the door into the sheepfold.`"
So if you turn from the Light, and stumble at the Light,
you stumble at all--and so will fall.
But if you love the Light, and are willing to follow the Light,
it will lead you through all--to deny yourselves, to take up the Cross unto yourselves,
and to pass through good report and evil report, through persecution, and through death;
and the way will not be grievous, but joyous.
And so you will come into the way, and enter at the door into the sheepfold,
and so into fellowship, and into life, and into the power,
and into the faith of the saints,
where all live in unity in One--united by One into one body.
Here you will find the end of all bickering and arguing, divisions and disputes.
Therefore, said the Apostle, "`Where is the wise?
Where is the disputer of this world?
Has not God made foolish the wisdom of this world?`"
"`I call you to come out from among them, and to be separate,
and to touch no unclean thing;`" and "`I will receive you, says the Lord;
and I will be unto you a Father, and you shall be my sons and daughters.`"

Now you are called, and this is the day of your visitation;
for now light is come into the world, and if you like to retain it in your minds,
happy are you; but if not, by it you are left without excuse,
and it will judge you in the last day.
For he that loves the light shall not walk in darkness, but shall have the light of life;
but he that does evil hates the light, and this is his condemnation.
Now, the way is plain to all simple ones, who have a desire to find it,
declared by a friend and witness to the Eternal Truth.

[.signed-section-signature]
James Parnell

--

James Parnell, having diligently labored in Cambridgeshire and Huntingdonshire,
passed into Essex, probably about the middle of the 5th month, 1655.
According to Stephen Crisp--"`The fields in that country were
white unto harvest:`" for there were very many whose spirits,
for some time, had gone heavily and wearily on their way under the burden of sin,
and who had sought among the different professions and opinions of
the day for a knowledge of that which could relieve them from it,
until they had become weary of seeking ways to escape.
"`In answer to the cry of His own seed,`" the Lord sent
James Parnell among them to preach the Word of life,
and to proclaim the acceptable year of the Lord.
Having preached the Gospel in many parts, such as Felstead, Stebbing, Witham, Coggeshall,
Halstead, and other places, where many hungry souls gladly received the Word of life,
and having planted many good meetings, and confirmed those that believed,
he at length went to Colchester, about the 6th month.
This was the place of Stephen Crisp`'s^
footnote:[Stephen Crisp became an eminent minister in the early Society of Friends,
laboring for the next thirty-five years in the power
and wisdom of the Spirit throughout England,
Scotland, Holland, and Germany.]
nativity, and where he then resided, being engaged as preacher among a separate people.

Stephen Crisp was educated in the national mode of worship.
He was from his earliest youth sensible of the visitations of
heavenly light (although not then knowing from where that light came),
which both reproved him for sin,
and caused peace and joy to spring up in his heart when he was obedient to its call.
But the carnal mind would arise and excuse sin, and lead him into transgression,
under the burden of which he was often made bitterly to mourn.
He sought various ways to escape from condemnation;
but while he remained "`the servant of sin,`" the light
of Truth pursued him with deep convictions,
and broke down his peace faster than he could build it up,
causing the fig leaf aprons of his own works (with which he would
attempt to cover his nakedness) to appear as tattered and filthy rags.
He says, he saw no further than his own works, as a means of bringing him peace with God.
He heard talk of Christ and Savior; but in the anguish of spiritual ignorance,
still had to exclaim, "`But, oh that I knew Him!`"

In those days, Stephen Crisp gave his ear to many religious disputes,
ran after the best ministers, and read sermons; but all was in vain.
He could not find rest, for he still felt the power of sin in him,
and longed for a way to overcome.
He applied to others in his distress,
both among the national church and separate professors; but none could help him.
So he continued to cry, "`Where is the faith which purifies the heart,
and gives victory?`"
The prevailing ignorance of the experiential work of religion
among those who were making a great profession of it,
had the effect of driving him away, for a time, from religion altogether,
to seek a joy and consolation in the world.
But the Lord`'s hand was too heavy for him there,
so that he soon returned to seek after something more substantial in religion.
Under these feelings, he submitted to water-baptism,
but soon had to mourn that this too was but a form without the power,
and it did no more than cleanse the outside,
but did not give him that inward cleansing which would enable
him to have "`the answer of a good conscience towards God.`"

Thus, finding that he still lacked what he had lacked before,
he told the elders of the Baptist church,
that "`God would soon overturn all their worships and religions,
which stood in outward and carnal things, and would make known some way above them all,
which should stand forever.`"
He had heard of the Quakers, and longed much to see some of them,
yet his carnal mind was able to reason much against some of their doctrines,
especially that of freedom from sin,
even though it was that for which he had all his life been longing.

He was about twenty-seven years of age when James Parnell came into Colchester.
When he first saw the youthful messenger,
he thought that he should be able to withstand him, and began to question him,
and endeavored to draw him into discourse.
But he soon found that James Parnell had a different spirit,
even a spirit of sound judgment, which was superior to his carnal reasoning.
Crisp was obliged to acknowledge the wisdom with which he spoke;
and said to those around, "`All our rods of Christian profession must be lost,
and be devoured by his.`"
On the day following, he went to a meeting appointed by James Parnell,
and so great was the authority with which he preached,
that Stephen Crisp was constrained to acknowledge and confess to the truth.

The very interesting and instructive account,
which Stephen Crisp gives of his own experience in religious matters,
previously to his meeting with James Parnell,
his feelings on first seeing this "`stripling,`" coming forth against
the Goliaths who had been too powerful for his own more matured years,
and greater acquaintance with the weapons of war, the inward contempt which he felt,
when he thought to withstand him by argument,
and his subsequent convincement of the Truth,
afford us striking evidence of the power and authority of James Parnell`'s ministry.
He was young, very small in stature, and of a poor appearance;
yet the wisdom of man was made to bow before that Spirit by which he spoke,
and of which he was the instrument.

[.offset]
The following original letter from James Parnell,
obtained from Colchester Monthly Meeting, was addressed to Stephen Crisp,
probably a short time after his convincement.
It is without date.

[.embedded-content-document.letter]
--

[.salutation]
Friend,

Stand in,
and keep your mind to that which lets you see your enemies to be of your own house.
Your imagination is an enemy; your wisdom is an enemy;
that which has been precious to you is now your greatest enemy.
Therefore, you must now sacrifice what you have called precious,
and yield it up to death, that the Just One may be raised to life,
and the righteous Seed be brought forth to reign in you and be your Head.
In this way the head of the serpent will be bruised.
In your measure, you will come to understand this,
as you dwell low in the Light which manifests your condition;
for "`whatever makes manifest is Light`" (Eph. 5:13).

Let that eye be kept open which the god of this world blinds in the children of the world.
For by this eye, the children of light can see their enemy, and so the tempter is known,
resisted, and denied.
So with this eye set a constant watch, and let not the fool`'s eye wander abroad,
which draws the wandering mind out after visible objects.
Rather, stand in the warfare, giving no place to the enemy or to his delusions,
but be content to become a fool, that all selfish thoughts may be judged.
Then you will receive wisdom from Him who gives generously and
without reproach to discern and know the enemy`'s schemes.
But know that it is in the cross to your own will and
hasty mind that the gift of God is received.
Therefore it is said "`He that believes will not act hastily`" (Isa. 28:16).

Therefore, be not weary of the yoke of the cross, for in faith it is made easy,
and the impatient nature is crucified, and patience has its perfect work.
So be still in the measure of Light which exercises your mind towards God.
Desire after nothing, but let your thoughts be judged, and let the power of God work,
that He may be seen to be all.
And by this principle alone you must be led and act,
keeping in the cross to the carnal part, and denying self,
both in the particular and in general.
And consider not who is displeased, so long as God is pleased,
for in this you give no just occasion of offense to any.
And though there is enmity in the world,
yet as this leads you to walk towards God in faithfulness,
so it also leads you to walk towards man with a conscience void of offense.
So keep your mind to the Light, and be not hasty to know anything beyond your measure,
for this is how Eve lost her paradise.
Rather, lie down low in the will of God and wait upon His teaching,
that He may be your Head,
and you will find the way of peace and dwell in unity with the faithful.
And though you are hated by the world, yet in God you will have peace and well-being.

[.signed-section-signature]
James Parnell

--

About ten years after,
Stephen Crisp was called upon to write a testimony to
the character and ministry of James Parnell;
which he did in a spirit which manifests,
that the remembrance of this instrument (by which his long wandering and weary soul
had been turned into the way which leads to an establishment in the Truth),
was still very precious.
After speaking of the great work which the Lord by His
own arm of power had wrought in those days,
he goes on to say:

[quote, , Stephen Crisp]
____
"`Babes have been His messengers, and children have been His ministers,
who in innocency have received the revelation of His Holy Spirit,
by which the deep things of His law, and of His glorious Gospel of life and salvation,
have been revealed.
And among these babes,
who thus came to receive a knowledge of the mysteries of the kingdom of God,
by the working of His divine power, was this noble child, James Parnell,
who was a vessel of honor indeed, and mighty in the power and Spirit of Emmanuel,
breaking down and laying desolate many mighty strongholds, and towers of defense,
in which the old deceiver had fortified himself and his children.
Much might be spoken of this young man, and a large testimony does live in my heart,
to his blessed life, and to the power and wisdom, that abounded in him.`"
____

The diligence with which James Parnell labored,
and the eagerness of the people to hear the Truth,
are strikingly exemplified in the account of his
services the day after he arrived at Colchester.
He went there on a seventh-day;
and on the first-day preached the Truth to many
thousands of people--first in his own lodging,
then in the Steeple-house after the sermon had concluded,
and then at a great meeting appointed for that purpose.
After this meeting, he disputed with the town-lecturer, and another priest,
in all of which "`the wisdom,
power and patience of Christ appeared very gloriously`" to the convincing of many,
who were witnesses of that day`'s work.

During the week he was diligently engaged "`preaching, praying, exhorting,
and admonishing, turning the minds of all sorts of professors to the Light of Jesus.`"
Many received the Truth which was declared unto them,
and found by a living and individual experience,
the reality and substance of that religion which, hitherto,
they had known only as a name.
But there were others who turned away from him, and refused to believe.
With these he disputed daily, "`with great soundness,
and in the evidence and demonstration of the Spirit,`"
by which the mouths of gainsayers were stopped,
and many more reached, and convinced of the Truth.

The prevalence of the Truth among the people stirred up the anger of many,
who "`gnashed their teeth at him,`" and some attempted to make up the deficiency in
their priests arguments by beating James Parnell with their fists and staffs.
Under the many affronts which he had to suffer,
"`his spirit was never seen to be raised in heat or anger,
but he was a pattern of meekness and patience,`" calm in disputation,
and not resentful under the infliction of personal injury.
One day, as he came out of the Nicholas Steeple-house, at Colchester,
someone struck him with a great staff, saying with blasphemous sarcasm: "`There!
Take that for Jesus Christ`'s sake.`"
To which James Parnell simply replied: "`Friend, I do take it for Jesus Christ`'s sake.`"
He stayed at Colchester, thus diligently laboring, and suffering for the Truth,
about ten days.

The promulgation of the true Christian principles, through James Parnell,
among a people who had long desired and expected a brighter day to arise upon the Church,
was attended by such great convincement,
that the priests and other professors began to be alarmed.
Through their instrumentality, and by their preaching,
many slanderous reports were raised against the Truth and its messengers.
They strove all they could, to hold it up as odious to the eyes of the people.
But when James Parnell came among them, to reply to their false accusations,
they turned away from a public support of their assertions, and left their congregations;
and James Parnell had thus an opportunity to proclaim still
further the true doctrines of the despised Quakers,
doubtless in a much more efficacious manner, than would have been the case,
had the preachers remained to dispute with him.
At length the priests began to appoint special meetings,
in order to attempt to persuade the people that the Truth was error and heresy; and so,
by incensing and prejudicing their minds,
to prevent them from hearkening to the Quaker-ministers.
And at the same time they sought their own protection,
and the suppression of their opponents,
by calling in the assistance of the secular powers.

James Parnell,
having heard that one of these meetings was appointed to be held at Great Coggeshall,
on the 12th of the 7th month, in order, as the priest publicly announced,
"`to fast and pray against the errors of the people called
Quakers,`" he felt drawn to be present at the meeting.
And, although he was persuaded that their object was to ensnare him and bring him into bonds,
should he go to Coggeshall to defend the principles which he had preached; yet, he said,
"`I was made willing, not only to be bound, but also to suffer for the pure,
eternal Truth, which I am made a witness of.`"
He manifested on this, and on other occasions, a striking desire to proceed orderly,
and to give as little cause of offense as possible, being, as he says,
"`pressed in spirit to go among them, in the behalf and defense of the Truth of God.`"
On the day of the meeting,
he left his Friends (probably assembled for
worship) without telling them where he was going.
Another Friend followed him to the door, and asked if he might accompany him.
James Parnell told him to use his freedom, but that he desired to go alone.

When he came to the Steeple-house, several children would have flocked in after him,
but he requested them to go in first, that no disturbance might be occasioned.
He entered orderly, and stood in silence,
while the priest was reviling and reproaching the Quakers.
When he had finished, and was leaving his seat, James Parnell said,
"`This is the order of the true Church, that all may speak one by one;
and if anything be revealed to him that stands by,
let the first hold his peace;`" (1 Cor. 14:30)
and then proceeded to speak on behalf of the People,
which the priest had ignorantly, and maliciously belied.
But he was soon interrupted by the priests, who "`ran out into many words,
and thus caused great confusion.`"
At length, he who had preached, asked James Parnell, "`what he could object against him?`"
To which he replied, "`in that he had reviled the Quakers,
and said they were built on a sandy foundation;
but he would prove their foundation not to be sandy, and him to be a false prophet.`"

He was then allowed to vindicate
"`the foundation of the Quakers--the real people; though perhaps not all who were called Quakers,`"
--which foundation was Jesus Christ,
the little stone cut out of the mountain without hands,
on which the true Church was ever built,
and which would break in pieces all that was in the mixture.
Some then accused him that he acknowledged no church.
He replied, "`I do acknowledge a church--the Church in God.`"
To which priest Willis, who had preached, said,
"`he speaks nothing but nonsense,`" and gave as an example of nonsense the
expression that Parnell had used-- "`the Church in God.`"
James Parnell then took out his Bible,
and showed them that it was a scriptural expression,^
footnote:[1 Thess. 1:1; 2 Thess. 1:1]
so that the priest and his companions were made ashamed.
After some further disputation,
they commanded James Parnell to put off his hat while the priest prayed;
but rather than do this, Parnell left the Steeple-house.

He was followed by one Justice Wakering and arrested,
but was allowed to go into a Friend`'s house till their worship was over,
where he spoke to the people who had come together.
Being afterwards brought before the Justices,
he was committed to the common jail at Colchester, as having been guilty,
"`with very many other persons of his gathering`" of "`a
riotous entrance into the parish church at Great Coggeshall,
of causing an unlawful assembly in the highway,
and using menacing and threatening speeches, tending to the breach of the peace.`"
The court order bears the date, "`the 12th day of July, 1655:`"
and is signed by Herbert Pellham, Thomas Cook, Dyonysius Wakering,
and William Harlackinden.

It was clear enough who were the chief actors in this persecution;
for when he was brought before the Justices, there were six or seven priests present;
four of whom were independents who were acting as parish-priests.
These preachers came from the different parts of Essex where
James Parnell had so effectually preached the gospel,
to the convincement of the people, and one of them spoke in public to the Justices,
in order to stir up their spirits to persecute.
"`Thus`" says James Parnell,
"`the churches gather themselves together against Christ and His kingdom;
and now the ravening wolves in sheep`'s clothing do appear; yes,
their fruits make them manifest.
These are they who call themselves Jews, but are not, but are the synagogue of Satan.
These are the builders who have rejected, and do reject, the precious Stone,
which has become the chief Cornerstone; and woe unto them upon whom it falls.`"

He was kept very close in prison,
none of his friends being permitted to see him "`with peace and freedom.`"
He occupied the time which transpired till the court session in
writing a reply to his court order (in which he clearly exposed its
falsities,) which he sent to the magistrates who committed him,
in order "`to clear his conscience.`"
The court sessions were to be held at Chelmsford,
which is twenty-two miles from Colchester;
to which he was obliged to walk being hooked with six felons to a chain.
He was coupled with one suspected of murder, and, along with three others,
was obliged to remain on the chain night and day.
"`Thus,`" James Parnell remarks,
"`I was led through the country for a gazing stock unto the world;
but Truth was preached in all this, and it prevailed on the hearts of the people.
Thus I could rejoice in all, and triumph over my enemies.`"

James Parnell, as if the chief felon,
was brought before the Judge with irons upon one hand;
but as some of the people cried out against this severity, on the next day,
when he was again brought up, the irons were removed.
A long indictment was read, containing the same charges as the court order,
and when several witnesses had given their testimony against him,
the reply which he had written to the charges, and sent to the justices,
was read openly in the court.
Judge Hills did all he could, by a wrong interpretation of Parnell`'s writings,
to incense the jury against him, and even went so far as to tell them that,
if they did not find him guilty, the sin would lie upon their own heads.
But he would not allow James Parnell to say a word in his own defense.
Notwithstanding this unjust conduct,
the jury returned and said they could charge him with nothing but the paper
he had written in reply to his court order after he was imprisoned;
and that they could not find him guilty of the charges in the indictment.
This, however, did not satisfy the judge,
and he at length succeeded in drawing some words from the
foreman (to which the rest of the jury did not consent) upon
which he assumed a legal power to re-commit Parnell to prison,
having imposed two fines to the value of about forty pounds--one for "`contempt of
the ministry,`" and the other for "`contempt of the magistracy,`" saying,
"`the Lord Protector^
footnote:[i.e. Oliver Cromwell]
had charged him to punish any such persons as should
show contempt for either magistracy or ministry.`"

Such were the unconstitutional proceedings of his enemies against him,
and some of his accusers were even allowed to stand upon the bench, near the Judge,
and frequently whisper in his ear during the trial.
But, he says, "`as the deceit of my enemies was manifested to many,
and caused them to acknowledge the Truth in their hearts, I was made to rejoice in all,
and my sufferings were not grievous, but joyous.`"
Not feeling liberty to pay the unjust fines which had been imposed,
he was remanded to prison; the Judge having given a special charge to the jailer,
not to allow any "`giddy-headed people`" (by which he meant Friends) to come to him.

On this occasion James Parnell remarks:

[.embedded-content-document]
--

"`So then they brought me back to prison again,
where I still remain in the peace and freedom of my spirit, which none can take away,
though my body be in the hands of my enemies.
Yet this I know, that the invisible God is working in secret by His power,
and with a strong arm is carrying on this great work which He has begun in the earth.
Yes, He will bring down and overturn all, until it comes into His hand,
to whom it belongs.
And He will exalt His kingdom in the hearts of His people,
and His Son shall rule over the earth.
All His enemies shall be His footstool, and shall bow unto Him,
and lay down their crowns before Him, and acknowledge His power.
Yes, He will dash all the lifeless forms, and false likenesses and images,
which have been set up by man in his own imaginations, and called churches.
He will dash them and the powers of the earth in pieces, one against another,
like a potter`'s vessel.
Though now they disdain the Cornerstone, yet then it shall grind them to powder.
For, '`our God is a consuming fire;`' and who is able to stand in the Day of His wrath?
It is a fearful thing to fall into the hands of the living God.
Therefore, woe to all His enemies, and to him who lifts up his hand against his Maker,
to do contrary to what He has decreed.`"

--

After the court session, James Parnell thought it right to send a letter to the Judge,
in which,
after complaining of the prejudice and injustice which he had manifested towards him,
he says: "`Consider what advantage it will be to you,
when you come to give an account before the Lord God of heaven and earth,
the Judge of all, the living and the dead,
if you now have power to keep this body in prison, or take my life,
which I am made freely willing to give up, rather than deny the Truth of my God?
And if I should pay one penny for the liberty of my body in this cause,
it would be as much as if I paid the whole fine, which you have unjustly laid upon me;
for by so doing, I should acknowledge myself a transgressor where I am not guilty.
And, also, a purchased liberty would be a bondage to my spirit,
but the liberty which I have, even under your bonds, is a bondage to you.
And this liberty which I feel, you cannot rob me of, by all that you can do;
for it is the free gift of God.`"

In Colchester Castle, James Parnell had now to undergo a series of cruel persecutions,
of an amount and character perhaps scarcely ever surpassed.
The jailer rigidly carried out the directions of the Judge,
not to allow his friends to come and see him,
as far as suited his own convenience or fancy.
James Parnell`'s youth, his character as a living minister of the Gospel,
his persevering diligence, and the sufferings he had already undergone,
excited great interest in the minds of Friends on his behalf.
Many came from considerable distances to visit him in prison,
but very few were allowed to see him.
Those who did, were obliged to purchase the permission of the jailer,
and then were much abused, and allowed to remain in his company but a very short time.
In a letter written to a friend, soon after the court sessions,
he recounts some of the indignities to which he was subjected,
and concludes saying:

[.embedded-content-document.letter]
--

"`Here I am committed to be kept a prisoner; but I am the Lord`'s free man,
and I know assuredly that He will judge and avenge my cause upon my adversaries.
And so I rest with confidence in Him, who will not leave nor forsake me,
for whose sake I suffer bonds, the time of His good will and pleasure.`"

--

But while those who wished to console and relieve him, were abused and shut out,
such as came to insult and scorn him, were allowed free admission.
These were even urged on by the jailer`'s wife,
who manifested a very bitter spirit towards Parnell, often directing her man to beat him,
and frequently beating him herself.
Such was her enmity against this innocent and unresentful victim, that she often swore,
"`she would have his blood, or he should have her`'s.`"
To which James Parnell would reply, "`Woman, I will have none of yours.`"

Sometimes they refused to give him food; at others,
they set the prisoners to steal the food when it was brought to him.
Some of his friends provided a trundle-bed for his use,
but they refused to allow him to have this accommodation,
and he was forced to lie on the stones, which, in the wet season,
would run down with water.
At first, he was allowed a room, for which he paid four-pence a night,
but at length they would not allow him even this.
The walls of the castle were exceedingly thick, with two rows of vaulted holes;
and into one of these holes (which looked like a baker`'s oven) they put James Parnell.
This hole was twelve feet from the ground,
and the ladder that was given him was only six feet long,
so that he was obliged to climb the remaining six feet by means of a rope.
The jailer would not even permit him to use a basket and cord to draw up his food,
but obliged him to fetch it on every occasion.
From living in this miserable, cold, and damp situation, his limbs grew numb,
and on one occasion, while attempting to return to his hole, he missed his footing,
and fell to the ground, receiving so severe an injury, that he was taken up as dead.
But the unrelenting jailer knew no pity,
and placed him in another little hole called the "`oven,`" lower down.
Here there was no window or opening, and when the door was shut,
he had scarcely any air or light.
When he had recovered a little from his fall, he was still kept closely confined,
and not allowed to go out for air.
On one occasion, the door of his hole was left open, and he walked out into the yard.
But seeing this, the jailer locked him out all night in the extremity of winter.

Amidst all this suffering he was not unmindful of his Friends, but,
as Stephen Crisp has remarked, "`he labored for the building up of those who were convinced,
and saw the desire of his soul concerning many,
for he lived to see the seed which he had sown, multiply and grow,
much to his refreshment.`"
Nor were his Friends unmindful of him, but labored earnestly to obtain, if possible,
a mitigation of his severe and cruel suffering; but all their efforts were in vain.
Then it might have been said,
as was said of the primitive members of Christ`'s Church-- "`See,
how these Christians love one another,`" for one of his Friends, Thomas Shortland,
offered to lie in prison, body for body,
that Parnell might have liberty to go to a friend`'s house, till he had recovered,
promising that his body should be returned if he died.
But this was refused, as well as a bond of forty pounds, offered by two other Friends.

In this state of suffering and hardship, he lived about ten or eleven months;
but after a time his constitution began to sink under it.
It appears that towards the latter part of his imprisonment, two Friends,
Anne Langley and Thomas Shortland, were allowed to visit him.
These were witnesses of his peaceful close,
and that his faith remained unshaken to the end.
He expressed to them his sense, that he "`died innocently;`" and said,
"`now I must go; this death I must die.`"
He further said, "`I have seen great things.`"
His last moments appear to have been remarkably calm.
He requested his friends "`not to hold him, but to let him go;`" and then, saying,
"`now I go,`" he stretched himself out and fell into a sweet sleep,
and having slept about an hour, breathed no more.

Thus died one, who in the very morning of his days,
had yielded his heart to the visitations of the Holy Spirit, and through faith, patience,
and steady obedience, became a mighty instrument in the Lord`'s hand,
to gather many into the Redeemer`'s fold of true rest.
He was interred in the Castle-yard, where the other prisoners were commonly buried,
because the jailer refused to give up the body without fees.

The malice of his enemies, however, did not terminate with his life;
but in order to cover their own cruelty, and to detract, if possible,
from the character of one whose life and death
had been a reproach to themselves (both as men,
and especially as professing Christians),
they industriously spread a report by various means that he had starved himself,
because during the last ten days of his life he was unable to take any food,
except occasionally a little milk and water.
Such a report, of course,
had no weight with the serious and reflecting part of the community, many of whom,
besides Friends, had been much interested in his sufferings,
and used efforts to obtain his liberation.
James Parnell was the first Friend who died in prison for his religion,
and his death appears to have produced considerable sensation among those in power,
who now professed to feel grieved that his case
had not claimed more of their consideration,
before it was too late.

It seemed better to me to recount the sufferings and death of this
faithful servant of the Lord during his last imprisonment,
than to break the narrative by the interspersion of other matter.
It may now be well to retrace our steps a little,
and see how he was employed during his rigorous confinement.
Men had the power to confine his body, but they could not limit,
nor control the operations of that Spirit which wrought in him.
His mind was active, amid outward sufferings and inconveniences of a kind and amount,
which seem to us, not only such as might excuse much labor for the Truth,
but even almost to preclude the possibility of doing much.
Yet his earnest spirit still remembered the Lord`'s heritage,
and from his lonely and suffering cell, he was concerned to address the newly convinced,
and to endeavor to build up, through various letters,
those churches which had been gathered by his instrumentality,
and to which he was no longer permitted to preach the Word of life.
And not only was his spirit concerned on behalf of believers, but also for the wicked,
whom he exhorted to turn away from their evil ways,
that they might not perish in the day of wrath and righteous retribution.
Some of these papers, written from James Parnell`'s cell, will be interesting,
as well as instructive.

[.offset]
Soon after he was re-committed to Colchester Castle, he wrote the following epistle:--

[.embedded-content-document.epistle]
--

[.letter-heading]
To Friends in the County of Essex

A few words to all my dear friends, in and about the County of Essex.

And all you, my dear friends, you scattered and despised ones, whom the Lord,
by His powerful Word, is now gathering out of darkness into marvelous light,
out of the kingdom of this world into the kingdom of His dear Son;
you whom He is separating unto Himself, to walk before Him in holiness,
that you might know Him, and He might know you in the light of His countenance;
you whose faces He has turned towards Zion,
to seek after a land of rest to your wearied souls,
which have been tossed to and fro from mountain to hill, in this cloudy and dark day,
seeking rest, but finding none:

Now has the Day of beauty broken forth near you, even in you.
Yes, and glad tidings have come unto your wearied souls,
by which a pure love to the Everlasting Truth is begotten in you,
which Truth has been freely declared among you by the messengers of the Most High,
who have reached the witness for God in your consciences,
which does seal the same upon your hearts.
He is your Teacher, unto whom you must hearken and be obedient.
Stand still in His light, and behold the work which the Lord has begun among us;
then you shall have no cause of discouragement, though the raging sea does rise,
and the raging waves do swell, as if they would swallow all up;
yet it is limited by the Unlimited One, and it shall but foam to its own shame.

And as I had a time to preach the Truth among you, to the convincement of many,
so now I have a time to seal the testimony with
patient suffering in the bonds of the Gospel,
that you may see that we preach no other than what we are
made able and willing to seal with patient suffering,
yes, even with our blood, if we are called to it, as many of us have done in this nation,
though this is called a land of liberty.
Indeed it is a land of liberty with respect to iniquity,
but truth and equity are strangers in it, and therefore are persecuted.
But you that are thought worthy to receive these strangers, happy are you.
And though the raging Sodomites compass you about,
to cause you to cast out these strangers, that they may work their wills upon them, yet;
be faithful, and fear them not; but cast out your darlings before them,
and stand in the faith of the God of truth and equity,
and you shall see the Sodomites struck with blindness,
and they shall not be able to prevail against you.
But when they are weary with striving, they shall be made to lie down in sorrow;
and so shall it be fulfilled, which was prophesied of old,
that "`no weapon formed against the faithful shall prosper;`"
but woe to them who lift up the heel against them.

Therefore I charge you all, in the name of the God of Truth, be faithful, valiant,
and bold for the Truth which you have received.
And as you have received it, so walk in it,
that you may profess no more in word than you possess in life;
and that the light may be preached forth in your lives, and shine forth in your conduct,
to the glory of the Father of lights, and the confounding of the heathen,
who profess God in words, but in life deny Him.

Be willing that self shall suffer for the Truth, and not the Truth for self,
(for the Truth was ever sealed with persecution,
since Cain`'s generation was upon earth,) and so embrace the cross, and despise the shame,
and give up to suffer for the Truth received,
all you who would follow the Lamb to the land of rest.
Through many trials you will grow strong and bold and confident in your God;
for God is not known, as to what a God He is, till the time of trial.

All keep your meetings in the name and fear of the Lord God, waiting for His power,
in the obedience to His light,
which in your consciences does reprove you when you do wrong.
Wait in His light, and watch over the foes that are of your own house,
that you may know a warfare begun in your hearts against your spiritual enemies.
Thus you will know the God of power Himself manifest among you by His mighty power,
bringing down all in you which opposes Him, and would not have Him to reign over you,
and exalt His own Seed in your hearts, and establish you in righteousness,
that you may bear His image; so that He shall be your God, and you shall be His people.`"

So, in the unchangeable Truth I rest, in unity with all the faithful,
in the glorious liberty of the sons of God, though in outward bonds for your sakes,

Known to all that can read me in spirit,

[.signed-section-signature]
James Parnell

--

[.embedded-content-document.epistle]
--

[.letter-heading]
To Friends in Essex.

Friends, To that gift of God in all your consciences I speak,
which there witnesses for God, and is according to the mind of God,
and is placed in your hearts to be your teacher--to teach you to do the will of God,
and how to walk according to the mind of God, and to distinguish between truth and error,
and between the precious and the vile,
and between him that serves the Lord and him that serves Him not.
This Teacher--the Light of Christ, enlightens your understandings,
and lets you see the land of darkness, where the house of bondage is,
where the righteous Seed lies oppressed, and where the man of sin rules,
and death has dominion.
This Light is your guide out of the house of bondage, and out of the land of darkness,
and out of death`'s dominion.
It slays the man of sin, and separates you from the children of darkness,
and leads you out from among them, to seek after another kingdom,
wherein is witnessed the perfect Day, where sorrow and sighing fly away.

But then, you must come out of yourselves,
and deny your own wisdom and reason and whatsoever springs
from self--for all of this is at enmity with the Light,
and opposes, argues, and contends against it, and by the Light is condemned.
If you hearken unto self, then you stumble in the way,
and many stumbling blocks lie before you, and thorns and briars catch hold of you,
and your feet stick in the mire.
There you toil in the bondage, and many hardships and impossibilities appear before you,
with doubts, fears, questionings, murmurings, and repinings.
There unbelief arises in you, and many temptations betake you.
Sometimes you are tempted to return and die in Egypt,
and sometimes to long after the delights and fleshpots of Egypt.
Sometimes to think that God has utterly forsaken you,
and sometimes to question the very Truth of God, and to be ready to call it a lie.
There, in self, is the wavering and unstable mind; and all this arises out of darkness,
where self stands; all comes by hearkening unto self.

Therefore, keep your minds unto the Light, the Messenger of God,
which brings the message of peace, and the glad tidings of salvation.
Keep close unto this, and know it alone to be your teacher, guide, and counselor,
in all the way through which you are to pass, and in all things that you are to do.
Stand in denial of self, and know the Light, which leads into singleness unto God,
and out of all selfish ends.
Then the Light will remove all stumbling blocks,
and lead you through the briars and thorns, and your feet shall not stick in the mire;
but the crooked way shall be made straight, and the rough and hard way plain and easy.
For in the Light there is no occasion of stumbling, but it keeps your feet from erring,
and your tongues from evil speaking, as you hearken unto it.
And when you are going to the right hand or to the left, it cries,
"`this is the way, walk in it.`"
This is the Word within you--from which faith comes,
which makes all things easy and possible;
but "`without faith it is impossible to please God.`"
And faith is the gift of God, and so is this Word of Truth, from which faith springs.
This will judge down all murmuring, doubting, and repining, and all carelessness,
lightness, lustings and earthliness,
and condemn the ground from which all these things spring.
And here the ministration of condemnation is witnessed (which is glorious in its time),
through which comes the ministration of peace, which exceeds the other in glory.
But take heed of getting these things into the comprehension, merely to talk of them.
Let the time of silence and patience have its work,
during which you must wait for the fulfilling of these things in you.
Then you will be able to read these things within,
and they will be made manifest in the life, which adorns and honors the Truth,
and so you will become vessels of honor.
But this cannot be witnessed without faithfulness;
for "`it is the willing and obedient that shall
eat the good of the land`" (Isa. 1:19).

Therefore, Friends, see that you stand in faithfulness to that which, in your measures,
is made known unto you; for faithfulness is of great value.
Faithfulness must be in secret and in public,
knowing that all things are public unto God,
who will judge the secrets of men by Jesus Christ.
Therefore, he that is faithful over a little, is approved of God,
and shall be made ruler over much; but he that is slothful is cast out,
and that which he has is taken from him.
These things you have read without, but now learn them within.
Read yourselves in the Light, and you will not be deceived;
for by the Light your hearts are searched, and by it all things are made manifest,
by which you are either approved or disapproved unto God, in all your words and actions.
Therefore, in this Light set a watch over all your thoughts, words, and actions,
that the righteous Judge may be set up in your hearts,
who condemns all deceit and iniquity, and establishes righteousness in the earth,
and truth and equity in the inward parts, and cleanses the heart from evil.
May this alone guide you, and be your spring of action in all your ways and doings.
And then self will have no part, but all things will be done in the cross to self,
in singleness unto God.
Then He alone is glorified, and His fear and awe are placed in the heart,
and the tongue is bridled, and the will curbed, and the heart cleansed, and kept clean;
for "`it is that which goes out of the heart that defiles.`"

Therefore, I say unto you all--watch, that the Pure One may exercise your minds,
who will crucify the carnal part, and mortify the deeds of the flesh,
and establish purity in the heart, and bring forth the fruit of the Spirit,
which is love in a pure life.
Here you may come to live, and walk and grow together in unity in your measures;
for that which separates from the unity is self, which causes love to grow cold.
But if you abide in the love of God, self is denied; and where self is embraced,
the love of God is denied.
Here you find the enemy in your own house, against which you are to war;
and in the Light which discovers self is your power and strength.
As you receive His Light, you receive power to deny self in its many appearances;
and this power reconciles your hearts one to another,
and brings you into a perfect friendship and unity which stands not in the will of man,
but in the pure nature.
This will be a cross to the worldly will, and the world will not bear it,
for it breaks the world`'s fellowship, love, and friendship,
all of which stand in the corrupt will of carnal men.
From here come all the world`'s customs, fashions, and traditions,
and all their worship and profession, and their persecution against you,
who dwell in the pure nature.
But look not out at what they can do to you,
knowing that at most they can take the life of the body.
But keep your eye to the Lord your God, in all your sufferings,
and count it your riches that you are found worthy to suffer for righteousness`' sake;
for it is through many trials and tribulations
that you will come forth pure unto the Lord,
and strong in the faith.

So, may the Lord God of power be with you,
and by His mighty power keep you low and watchful in your conditions,
that you may regard your eternal good above all things under the sun.
May every one of you walk and grow in the Truth which you have received,
daily dying unto the things which perish, that you may come to dwell in the life of God,
out of created things; and then the true use of them will be given you,
along with the pure wisdom, as it was in the beginning,
when man was in the right use of created things.
Here paradise will indeed be found.
But "`he that believes makes not haste;`" (Isa. 28:16) and by "`patient
continuance in well-doing,`" you will reap if you faint not.

Dear friends, it is the love of God in me, which speaks unto the Seed in you,
that constrained me to write unto you, and visit you with this epistle.
Though my bodily presence is kept from you (by the corrupt will of man),
yet my spirit does not cease to cry on your behalf,
that the Lord by His power (by which He has awakened you out of sleep,
and caused His witness to answer to His Truth) would
bless and prosper His happy work in your hearts,
to the bringing forth of His precious Seed to rule and have dominion.
May His glorious Light shine forth in your conduct, and His beauty appear in your image,
that the heathen may be ashamed and fear before the Lord your God.
And here, my friends, is my comfort in the midst of bonds: yes,
if this body was to be sacrificed up, it would not abate my joy that I have in you,
in whom the work of God prospers.
Therefore, I charge you all in the name of the living God, whom you profess,
to abide diligently and circumspectly in His fear, that you grieve not the Spirit of God,
nor cause His holy name to be blasphemed,
lest you add affliction to the bonds of the Gospel.

This from a friend, who is known in spirit,
who for the innocent Seed`'s sake suffers the bonds of the Gospel.

[.signed-section-signature]
James Parnell.

[.signed-section-context-close]
From Colchester Castle, The 11th month, 1655

--

[.embedded-content-document.letter]
--

[.letter-heading]
James Parnell to William Dewsbury

[.salutation]
For my dear brother William Dewsbury in the Common Jail at Northampton,

Dear and precious brother in the eternal, unchangeable Truth of God,
I do, in my measure, dearly salute you.
You are blessed of the Lord, dear brother.
Your fatherly care over me I do acknowledge, and your voice is a comfort to me.
I am kept and nourished in the midst of my enemies--glory be to God in the highest,
who has counted me worthy to bear the bonds of the Gospel.

Dear Brother--I am glad to hear from you, and of my dear brother, Thomas Stubbs,
with you, whom I love in the Lord, and the rest of my fellow-prisoners.
The Lord has set you a father over them.
I know your burden is great, for the work lies upon you, but your joy is in your children.

Truly there is a great appearance in these parts,
but there is much need of a minister since I was cast in bonds.
But I had good liberty among them, before they were permitted to lay hold on me.
And great was the work of the Lord, and it spread very much, to my great comfort.
And now these bonds have been very serviceable, to the piercing of the hearts of many,
and the discovery of the spirit of my persecutors,
and to the confirming of those in the Truth that were convinced.
They have labored to make my bonds grievous, but my strength the Philistines know not.
Friends are much barred from visiting me, yet not all.
Our tender sister, M. S. is here in bonds in the town prison--she
was put in last evening for speaking to a priest.
She has been in twice before this within a week, but they had no power to keep her in.

So may the same power that keeps you, keep me; and let your prayers be for me.
I rest with you in the brotherly unity, your tender brother,

[.signed-section-signature]
James Parnell.

[.signed-section-context-close]
Colchester Castle, 16th of 12th month, 1655

--

[.embedded-content-document.epistle]
--

[.letter-heading]
An Epistle to Friends.

All you friends of the Light, though we who are your ministers and messengers of Light,
be cast into prisons, holes, and dungeons, and are kept there by the devilish,
corrupted will of man, and it be allowed by God, the Father of Light,
for the fulfilling of the Scriptures upon that generation (which was
prophesied of by the ministers and messengers of Light in the days of old,
who suffered in the same nature, by the same generation, for the same testimony);
and though the Lord yet allows the same generation to act in this nature against us,
and fill up their measure of wrath, it is for the manifestation of His Truth,
and exaltation of His name and power.

Through all this, are we known, and made manifest unto you, who are in the Light;
and even the unbelievers come to know and confess that He is greater that is with us,
than all they that can rise up against us.
And in all this we do rejoice, and, through our sufferings we are crowned,
and get the victory over the world without, as well as within.
And though we are kept in prison, yet it is for the Lord`'s appointed time.
Therefore, Friends, keep your eye to the Lord in all these things,
and look not out at man, nor at what man can do, either for or against us.
Keep your eye to God in all His works, and in all His instruments,
and there will be no cause for discouragement; for discouragement and fears,
doubts and questionings, spring from the carnal mind.
But there is an eternal Witness in all your consciences, which, by the Word of power,
is awakened in you.
By this we are known, by it we are acknowledged,
by it we are witnessed and received into your hearts, wherein our unity stands with you,
who are faithful unto it, and by it we are remembered, though far absent in body.

And this Witness we also have in the men of the world, though they do not receive it,
nor like to retain it in their minds.
For this reason they do not receive us, but as the Witness lies slain in them,
therefore they strive to slay us; and indeed, this is their condemnation,
which will witness unto God against them, out of their own mouths.
And thus, we are made a sweet savor unto God, both in you that believe,
and in them that perish.
Therefore, you that do believe, take heed unto this Witness,
and mind its answer in your consciences,
that it may exercise your consciences in unity with God,
that you may be kept in the sense of it,
and be taught and guided by it into the cross to your own wills,
that the will of God may guide you, and not your own will.
Then will the living Witness be raised up in you, to live, and rejoice, and be your head;
and that which has been your head, may be bruised.
In this way, Friends,
your hearts will come to be established and confirmed in the unchangeable Truth,
unto which you are called, that you may be the children of Truth.
So all you who acknowledge this voice,
keep close to the Witness in your own minds and consciences,
that you may feed upon the living substance at the table of the Lord,
and there partake of the union and communion of saints.
As every one of you dwell in your own measures,
the things of God will come to be cleared up to you, and the shadows will vanish away.

Keep at home, every one, in your tents, and let the candle stand upon the candlestick,
that the whole house may be enlightened--lest the thief get in at a secret corner,
and trouble you, and rob you, and cast a veil over your light.
While you have the light, abide in it, and in it you will see more light,
to sweep clean within, and search every corner,
and permit not an enemy to remain in the house.
Cast out that which has been in your bosom, and let the Lamb be there, who has said,
"`He that loves anything better than me, is not worthy of me.`"
So, bring all unto the Light, and woe unto him that hides from the Light,
for the Day will make him manifest.

Oh, rest not above the Life, nor feed upon anything below it!
Follow the Light, which leads your minds unto the Son; for in Him is peace, yes,
true peace, which cannot be broken.
He is the bond of peace.
If you abide in Him, He will abide in you, and you shall bring forth fruit plentifully.
He will refresh you with the heavenly dew, and you shall flourish, as in a summer`'s day,
yes, as plants of righteousness.
But the spring comes first.
Oh how pleasant and beautiful is the spring in a barren field,
where barrenness and deadness fly away!
As the spring comes on, the winter sheds her coat, and the summer is nigh.
Oh, wait to see and read these things within!
You, that have been barren and dead and dry, without sap,
unto you the Sun of righteousness is risen with healing in His wings,
and begins to shine in your coasts.
For this is the Day wherein the Lord is come to visit you; yes,
to you who have long sat in darkness, now light has sprung.
Oh mind the secret spring!
Mind the tender plants!

Now you are called to tend and keep the garden; let not the weeds and wild plants remain.
Peevishness is a weed; anger is a weed; self-love and self-will are weeds;
pride is a wild plant; covetousness is a wild plant;
lightness and vanity are wild plants; and lust is the root of all.
These things have had room in your garden, and have been tall and strong; and truth,
innocency, and equity, have been left,
and could not be found until the Sun of righteousness arose,
and searched out that which was lost, and brought back that which was driven away.
Therefore, do not stand idle, but come into the vineyard and work.
Your work shall be to watch, and keep out the fowls of the air, the unclean beasts,
the wild bears, and the subtle foxes.
And He that is the Husbandman, will pluck up the wild plants and weeds,
and make a defense around the vines.
He will tell you what to do.
He, who is Father of the vineyard, will be near you.
Now, read within, or you will stumble; and whatever is not clear to you, wait for it,
knowing, "`He that believes, makes not haste.`"
But, you who are covered with fig-leaves only, the Son will search you.
You must come to the fall of the leaf, and to the time of deadness and winter,
before the life will appear and the living springs be opened.
You must cast off your own garments,
and then the Son will clothe you--but not before you are made naked.
For truly, shame must come upon all flesh,
and you must not have even an apron of fig-leaves to cover your nakedness.

[.signed-section-signature]
James Parnell

[.signed-section-context-close]
This Epistle has no date, but there is no doubt it was written from Colchester Castle.

--

[.offset]
The following letter bears the latest date of any of James Parnell`'s writings,
as far as I have been able to discover.
It was written about five months from the time of his first imprisonment;
but as there were many letters written by him during his
confinement in Colchester Castle which have not been preserved,
it is probably not the last he wrote: it is addressed:

[.embedded-content-document.epistle]
--

[.letter-heading]
To Friends in London

[.salutation]
To my dear Friends, brethren, and sisters in the city of London.

To you translated ones, my love from the life does flow.
To you that are translated and renewed in heart and mind;
you that are separated and redeemed from among the children of this world,
and the pollutions and abominations that they live in;
in whom the works of the new creation, wherein righteousness dwells, are established.
To you who are beautiful within, who are adorned within,
who are purified and cleansed within by the precious Blood of the Lamb,
with whom you are crucified--who are in Him, who have put on the wedding garment,
and are admitted to the table of the Lord, and are partakers of the holy union.

Oh, you blessed of the Lord, you babes and children of the Most High
who dwells in purity and reigns in majesty,
who has established and set up His throne in
your hearts--in you is my joy and great delight.
Yes, I remember when you were tender and just springing up, but now,
by waiting on the Lord, you have renewed your strength, and my joy is made full in you,
and you are made precious in my sight.
You indeed have become inward Jews, of the heart-circumcision, redeemed from kindred,
tongues, languages and people, who have come to the heavenly Jerusalem,
there to worship the Father in Spirit and in truth.
He has chosen you to bear His holy image (which has been so much defaced in
the world) and in you to exalt and glorify His holy name among the heathen,
and those who do not know Him in this Day,
wherein He is visiting the earth with judgment and with mercy, and with mighty power,
to call to an account the inhabitants of the earth.

Blessed are you who have hearkened unto His voice; for you shall sing and rejoice,
when others shall weep, and mourn, and howl.
Though your portions now among them be suffering, scorning, mocking, deriding,
backbiting, reviling, persecution, stripes, and imprisonments,
yet have you learned to count these things as riches, who know the Comforter within you,
and your Redeemer to live with you.
I do rejoice in all these things, being now made a partaker of them.
Oh how do I long to see your faces, but in that I am restrained for a time!
My life is bound up in many of your hearts, which makes it so that I cannot forget you,
though my body is kept in strait bonds.
But the bonds will be broken by Him who is my only keeper and supporter,
when He has perfected His praise in them.

Oh, you simple doves, who sit without deceit in your mouths!
Oh, how I am ravished with the love of you when I behold you in spirit!
You that have given yourselves up unto death, to the famine, to the sword,
and to the fire, and have patiently submitted unto the Father`'s will,
and willingly sacrificed up your precious things.
Your faith is unto you imputed for righteousness,
and the God in whom you have trusted and believed will make you rich in Him,
and give you substance incorruptible, and an inheritance that never fades.
In measure you can set your seals to what is now written unto you.

But some have listened to the evil spirit,
which has brought evil tidings of the good land.
Such have turned back to Egypt,
and joined with its magicians to harden Pharaoh`'s heart against the innocent,
and filled the mouths of the heathen with blasphemous speeches.
But let them go on;
"`he that is filthy, let him be filthy still;`"
for the Lord comes quickly, whose reward is with Him,
to give unto all according to their doings.
But all things work together for the good of you, who stand in the faith,
who are not moved with the winds that blow, nor the storms that come against you,
who keep your eye to the hand of Providence in all these things.
This brings good out of evil to all who abide in the Truth, and do not stray.

So, as you have tasted, felt, known, and experienced Him, so trust in Him,
and remain in your sure confidence, which is begotten in you by His Word.
Be as lights in the dark world both by word and conduct,
that in all things you may be approved by the Father`'s Spirit in your consciences,
as faithful and obedient children, every one in your calling wherein you are called,
that you may obtain the prize in the end of your race.
Oh, lift up your heads, and look up to the Father, and see how He has been tender to you,
and how His love has been offered to you all along,
who has not left you without instructors and nursing fathers,
who have watched over you with tender care.
In much love and tenderness I am drawn forth towards you little ones,
who spring from the root of the Vine, because you bear my Father`'s image.
Long have I waited to write to you, and lately I had an opening of you,
which caused me to visit you with this epistle;
for you have oftentimes been in my remembrance, though I could not write.
And now you must read me in that love, which tongue cannot express,
and in that epistle which is written in your hearts, without either paper or ink,
by the immortal Word of life, and there you will know my name.

So, the Lord God Almighty, the keeper of Israel, overshadow you,
and may He keep you pure and innocent in His holy presence,
that you may show forth His praise in the earth,
and shine as the sons and daughters of Zion.
I commit you into His blessed protection, and do lie down with you,
who am a sufferer in outward bonds by the will of men for the innocent Seed`'s sake,
but am at liberty with the faithful.

[.signed-section-signature]
James Parnell.

[.signed-section-context-close]
Written from Colchester Castle, The 12th of 1st Month,1656

--

These letters bear a precious stamp,
which evidences the writer to have been a true child of God through Jesus Christ.
We cannot doubt, as was remarked by Thomas Bayles respecting him,
that "`he was hated and persecuted for righteousness`' sake,
and for testifying against the gross hypocrisy of that day.`"
The cruel, bitter, and unrelenting spirit of persecution, which his enemies manifested,
and so long exercised towards him,
too clearly shows that they were the children of that Babylon,
of whom it was prophesied that,
she would be made drunk with the blood of the Lord`'s children.
The entire dedication of James Parnell to the Lord`'s service--his meekness under wrong,
his patience under suffering and insult,
the steadfast integrity of his heart through a long period, not of suffering only,
but of bitter mocking and subjection to the taunting and jesting of wicked men,
his fervent love of the brethren while he was in bonds,
and the tender breathing of his very soul that they might,
through obedience to the Light received, come to know God and His Son truly,
and ever dwell under the protecting wing of infinite Love--all
of this manifests that he was a man redeemed from the world,
and affords the strongest assurance that, "`through much tribulation,
he has entered the kingdom of heaven,`" and is now wearing the
crown promised to all those who are "`faithful unto death.`"
